// resources/js/Pages/Auth/VerifyEmail.vue
<script setup>
import { computed } from 'vue';
import GuestLayout from '@/Layouts/GuestLayout.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import { Head, Link, useForm } from '@inertiajs/inertia-vue3';

const props = defineProps({
    status: String,
    email: String
});

const form = useForm({
    email: '',
});

const submit = () => {
    form.email = props.email;
    form.post(route('verification.send'));
};

const verificationLinkSent = computed(() => props.status === 'verification-link-sent');
</script>

<template>
    <GuestLayout>

        <Head title="Ativar Conta" />

        <div class="mb-4 text-sm text-gray-600">
            Sua conta já foi criada! Antes de começar, confirme o seu endereço de cadastro clicando no link presente no
            e-mail que te enviamos. Caso não tenha recebido o email, teremos o maior prazer em te enviar outro.
        </div>

        <div class="mb-4 font-medium text-sm text-green-600" v-if="verificationLinkSent">
            Um novo link de verificação foi enviado para o endereço de e-mail de cadastro..
        </div>

        <form @submit.prevent="submit">
            <div class="mt-4 flex items-center justify-between">
                <PrimaryButton :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Enviar novamente o e-mail de verificação
                </PrimaryButton>
            </div>
        </form>
    </GuestLayout>
</template>

// frontend/src/app/pages/verify-email/verify-email.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { ToastService } from '../../services/toast.service';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-verify-email',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './verify-email.component.html',
  styleUrls: ['./verify-email.component.scss']
})
export class VerifyEmailComponent implements OnInit {
  private readonly http: HttpClient = inject(HttpClient);
  private readonly route: ActivatedRoute = inject(ActivatedRoute);
  private readonly router: Router = inject(Router);
  private readonly toastService: ToastService = inject(ToastService);
  private readonly apiUrl = environment.apiUrl;

  email: string = '';
  processing = false;
  verificationLinkSent = false;

  ngOnInit() {
    this.email = this.route.snapshot.queryParams['email'] || '';
    if (!this.email) {
      this.toastService.error('E-mail não fornecido.');
      this.router.navigate(['/login']);
    }
  }

  submit() {
    if (!this.email) return;

    this.processing = true;
    this.verificationLinkSent = false;

    this.http.get(`${this.apiUrl}/sanctum/csrf-cookie`).subscribe({
      next: () => {
        this.http.post(`${this.apiUrl}/email/verification-notification`, { email: this.email }).subscribe({
          next: (response: any) => {
            this.processing = false;
            if (response.status === 'verification-link-sent') {
              this.verificationLinkSent = true;
              this.toastService.success('Link reenviado com sucesso!');
            } else if (response.message === 'Email already verified.') {
              this.toastService.info('Conta já ativada! Você pode fazer login.');
              this.router.navigate(['/login']);
            }
          },
          error: (err: HttpErrorResponse) => {
            this.processing = false;
            this.toastService.error('Erro ao enviar o e-mail de verificação.');
            console.error('Error sending verification email:', err);
          }
        });
      },
      error: (err: HttpErrorResponse) => {
        this.processing = false;
        console.error('CSRF setup failed', err);
      }
    });
  }
}

<div class="bg-gradient-primary min-vh-100 d-flex flex-column justify-content-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Ativar Conta</h1>
                                    </div>
                                    
                                    <div class="mb-4 text-sm text-gray-600">
                                        Sua conta já foi criada! Antes de começar, confirme o seu endereço de cadastro clicando no link presente no e-mail que te enviamos. Caso não tenha recebido o e-mail, teremos o maior prazer em te enviar outro.
                                    </div>

                                    <div class="alert alert-success" role="alert" *ngIf="verificationLinkSent">
                                        Um novo link de verificação foi enviado para o endereço de e-mail de cadastro.
                                    </div>

                                    <form class="user" (ngSubmit)="submit()">
                                        <button type="submit" class="btn btn-primary btn-user btn-block" [disabled]="processing" [class.opacity-50]="processing">
                                            <span *ngIf="processing" class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
                                            Enviar novamente o e-mail de verificação
                                        </button>
                                    </form>

                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="/login">Voltar ao Login</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
