// frontend/src/app/pages/transport/brand/brand.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
 
import { BrandService, Brand, BrandCreateUpdateRequest } from '../../../services/brand.service';
import { ToastService } from '../../../services/toast.service';
import { AuthenticatedLayoutComponent } from '../../../shared/layouts/authenticated-layout/authenticated-layout.component';
import { ConfirmModalComponent } from '../../../shared/components/confirm-modal/confirm-modal.component';
import { DatatableComponent } from '../../../shared/components/datatable/datatable.component';
import { ModalComponent } from '../../../shared/components/modal/modal.component';

@Component({
  selector: 'app-brand',
  standalone: true,
  imports: [CommonModule, FormsModule, AuthenticatedLayoutComponent, ConfirmModalComponent, DatatableComponent, ModalComponent],
  templateUrl: './brand.component.html',
  styleUrls: ['./brand.component.scss'],
})
export class BrandComponent implements OnInit {
  private readonly brandService: BrandService = inject(BrandService);
  private readonly toastService: ToastService = inject(ToastService);
 
  brands: Brand[] = [];
  inEdition: number = 0;
  isLoader: boolean = false;
  processing: boolean = false;
  errors: any = {};
  showModal: boolean = false;
 
  // Pagination and Filtering state
  pagination: any = {
    current_page: 1,
    per_page: 10,
    total: 0,
    last_page: 1,
    from: 0,
    to: 0,
  };
  searchQuery: string = '';
  sortColumn: string = 'id';
  sortDirection: string = 'desc';
 
  form = {
    id: 0,
    name: '',
  };
 
  ngOnInit(): void {
    this.loadBrands();
  }
 
  loadBrands(): void {
    this.isLoader = true;
    const params = {
      page: this.pagination.current_page,
      per_page: this.pagination.per_page,
      search: this.searchQuery,
      sort_column: this.sortColumn,
      sort_direction: this.sortDirection,
    };
 
    this.brandService.getBrands(params).subscribe({
      next: (response: any) => {
        this.brands = response.data || [];
        this.pagination = {
          current_page: response.current_page,
          per_page: response.per_page,
          total: response.total,
          last_page: response.last_page,
          from: response.from,
          to: response.to,
        };
        this.isLoader = false;
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao carregar marcas');
        console.error('Erro ao carregar marcas:', error);
      },
    });
  }
 
  onSearch(query: string): void {
    this.searchQuery = query;
    this.pagination.current_page = 1;
    this.loadBrands();
  }
 
  onPageChange(page: number): void {
    this.pagination.current_page = page;
    this.loadBrands();
  }
 
  onPerPageChange(perPage: number): void {
    this.pagination.per_page = perPage;
    this.pagination.current_page = 1;
    this.loadBrands();
  }
 
  sortBy(column: string): void {
    if (this.sortColumn === column) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortColumn = column;
      this.sortDirection = 'asc';
    }
    this.loadBrands();
  }
 
  openModal(): void {
    this.resetForm();
    this.showModal = true;
  }
 
  closeModal(): void {
    this.showModal = false;
    this.resetForm();
  }
 
  edit(brand: Brand): void {
    this.inEdition = brand.id;
    this.form.id = brand.id;
    this.form.name = brand.name;
    this.errors = {};
    this.showModal = true;
  }
 
  cancelEdit(): void {
    this.closeModal();
  }
 
  resetForm(): void {
    this.form = {
      id: 0,
      name: '',
    };
    this.errors = {};
    this.inEdition = 0;
  }
 
  private validateForm(): boolean {
    this.errors = {};
 
    if (!this.form.name || this.form.name.trim() === '') {
      this.errors.name = ['O nome é obrigatório'];
      return false;
    }
 
    return true;
  }
 
  submit(): void {
    if (!this.validateForm()) {
      return;
    }
 
    this.processing = true;
 
    const data: BrandCreateUpdateRequest = {
      id: this.form.id,
      name: this.form.name,
    };
 
    this.brandService.saveBrand(data).subscribe({
      next: (response: any) => {
        this.processing = false;
        this.toastService.success(response.message || 'Marca salva com sucesso');
        this.closeModal();
        this.loadBrands();
      },
      error: (error: HttpErrorResponse) => {
        this.processing = false;
        if (error.status === 422) {
          this.errors = error.error.errors || {};
        } else {
          this.toastService.error('Erro ao salvar marca');
        }
        console.error('Erro ao salvar marca:', error);
      },
    });
  }
 
  deleteBrand(brandId: number): void {
    this.isLoader = true;
    this.brandService.deleteBrand(brandId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Marca apagada com sucesso');
        this.loadBrands();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao apagar marca');
        console.error('Erro ao deletar marca:', error);
      },
    });
  }
 
  activateBrand(brandId: number): void {
    this.isLoader = true;
    this.brandService.activateBrand(brandId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Marca ativada com sucesso');
        this.loadBrands();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao ativar marca');
        console.error('Erro ao ativar marca:', error);
      },
    });
  }
 
  deactivateBrand(brandId: number): void {
    this.isLoader = true;
    this.brandService.deactivateBrand(brandId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Marca inativada com sucesso');
        this.loadBrands();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao inativar marca');
        console.error('Erro ao inativar marca:', error);
      },
    });
  }
 
  isBrandInEdition(brandId: number): boolean {
    return this.inEdition === brandId;
  }
}

<app-authenticated-layout>
  <ng-container header>
    <div class="d-sm-flex align-items-center justify-content-between mb-4 animate-in">
      <h1 class="h3 mb-0 text-gray-800">Gerenciamento de Marcas de Veículo</h1>
    </div>
  </ng-container>

  <div class="row position-relative">
    <!-- Modal de Cadastro/Edição -->
    <app-modal [show]="showModal" (close)="closeModal()" [title]="inEdition > 0 ? 'Editar Marca' : 'Cadastrar Nova Marca'" icon="fa-edit" size="md">
      <form (ngSubmit)="submit()" class="d-flex flex-column flex-grow-1 min-h-0">
        <div class="form-group mb-3">
          <label for="name" class="form-label">
            Nome da Marca:
            <span class="text-danger">*</span>
          </label>
          <input
            type="text"
            id="name"
            class="form-control"
            [class.is-invalid]="errors['name']"
            [(ngModel)]="form.name"
            name="name"
            placeholder="Ex: Toyota"
            required
            autofocus />

          <div *ngIf="errors['name']" class="text-danger mt-1">
            <small *ngFor="let err of errors['name']" class="d-block">{{ err }}</small>
          </div>
        </div>
        <div class="modal-footer px-0 pb-0 pt-3 d-flex justify-content-end gap-2 border-top">
          <button type="button" class="btn btn-outline-secondary" (click)="closeModal()" [disabled]="processing">
            <i class="fas fa-times me-1"></i>
            Cancelar
          </button>
          <button type="submit" class="btn btn-primary shadow-sm" [disabled]="processing">
            <span *ngIf="processing" class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
            <i *ngIf="!processing" class="fas fa-save me-1"></i>
            Salvar
          </button>
        </div>
      </form>
    </app-modal>

    <!-- Table Section -->
    <div class="col-lg-12 animate-in" style="animation-delay: 0.2s">
      <div class="card mb-4 border-left-secondary">
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between mb-4">
            <h5 class="card-title mb-0 text-secondary font-weight-bold">
              <i class="fas fa-list me-2"></i>
              Lista de Marcas
            </h5>
            <button class="btn btn-primary btn-sm shadow-sm" (click)="openModal()" [disabled]="processing">
              <i class="fas fa-plus me-1"></i>
              Nova Marca
            </button>
          </div>

          <app-datatable
            [pagination]="pagination"
            [loading]="isLoader"
            (search)="onSearch($event)"
            (pageChange)="onPageChange($event)"
            (perPageChange)="onPerPageChange($event)">
            <div class="table-responsive">
              <table class="table table-hover" width="100%" cellspacing="0">
                <thead class="table-light">
                  <tr>
                    <th scope="col" (click)="sortBy('id')" style="cursor: pointer; width: 80px">
                      <div class="d-flex align-items-center">
                        ID
                        <i
                          class="fas fa-sort ms-2 text-muted"
                          [ngClass]="{
                            'fa-sort-up text-primary': sortColumn === 'id' && sortDirection === 'asc',
                            'fa-sort-down text-primary': sortColumn === 'id' && sortDirection === 'desc',
                          }"></i>
                      </div>
                    </th>
                    <th scope="col" (click)="sortBy('name')" style="cursor: pointer">
                      <div class="d-flex align-items-center">
                        Nome
                        <i
                          class="fas fa-sort ms-2 text-muted"
                          [ngClass]="{
                            'fa-sort-up text-primary': sortColumn === 'name' && sortDirection === 'asc',
                            'fa-sort-down text-primary': sortColumn === 'name' && sortDirection === 'desc',
                          }"></i>
                      </div>
                    </th>
                    <th scope="col" class="text-end">Ações</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let brand of brands" [class.table-info]="isBrandInEdition(brand.id)">
                    <th scope="row" class="font-weight-bold">{{ brand.id }}</th>
                    <td>
                      <span [class.text-muted]="!brand.active">{{ brand.name }}</span>
                      <span *ngIf="!brand.active" class="badge bg-light text-muted ms-2">Inativo</span>
                    </td>
                    <td class="text-end">
                      <div class="d-flex justify-content-end gap-2 flex-wrap">
                        <button class="btn btn-info text-white shadow-sm btn-action" (click)="edit(brand)" data-tooltip="Editar Marca">
                          <i class="fas fa-edit"></i>
                        </button>

                        <button *ngIf="!brand.active" class="btn btn-success shadow-sm btn-action" (click)="activateBrand(brand.id)" data-tooltip="Ativar Marca">
                          <i class="fas fa-check"></i>
                        </button>

                        <app-confirm-modal
                          *ngIf="brand.active"
                          [btnClass]="'btn btn-warning shadow-sm btn-action'"
                          [modalTitle]="'Inativar Marca'"
                          [message]="'Tem certeza que deseja inativar a marca ' + brand.name + '?'"
                          [okButtonLabel]="'Confirmar'"
                          [tooltip]="'Inativar Marca'"
                          (confirm)="deactivateBrand(brand.id)">
                          <span modal-button>
                            <i class="fas fa-ban"></i>
                          </span>
                        </app-confirm-modal>

                        <app-confirm-modal
                          [btnClass]="'btn btn-danger shadow-sm btn-action'"
                          [modalTitle]="'Excluir Marca'"
                          [message]="'Ação irreversível! Deseja realmente excluir a marca ' + brand.name + '?'"
                          [okButtonLabel]="'Excluir'"
                          [tooltip]="'Excluir Marca'"
                          (confirm)="deleteBrand(brand.id)">
                          <span modal-button>
                            <i class="fas fa-trash"></i>
                          </span>
                        </app-confirm-modal>
                      </div>
                    </td>
                  </tr>
                  <tr *ngFor="let i of [1, 2, 3, 4, 5].slice(0, isLoader ? 5 : 0)">
                    <td colspan="3" class="text-center py-3">
                      <div class="placeholder-glow">
                        <span class="placeholder col-12 rounded"></span>
                      </div>
                    </td>
                  </tr>
                  <tr *ngIf="brands.length === 0 && !isLoader">
                    <td colspan="3" class="text-center py-5 text-muted">
                      <i class="fas fa-folder-open fa-3x mb-3 d-block opacity-25"></i>
                      Nenhuma marca encontrada.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </app-datatable>
        </div>
      </div>
    </div>
  </div>
</app-authenticated-layout>

// resources/js/Pages/Auth/Auxiliaries/Brand.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import Modal from '@/Components/Modal.vue';
import Loader from '@/Components/Loader.vue';
import { Head, useForm } from '@inertiajs/inertia-vue3';
import { onMounted, ref } from 'vue';

const props = defineProps({
    brands: Array
});

const inEdition = ref(0);

const form = useForm({
    id: 0,
    name: '',
});

const formDelete = useForm({
    id: 0
});

const isLoader = ref(false);

onMounted(() => {
    $('table').DataTable({
        language: {
            url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/pt-BR.json',
        },
    });
});

const deleteBrand = (id) => {
    isLoader.value = true;
    formDelete.id = id;
    formDelete.delete(route('brand-delete'), {
        onFinish: () => {
            isLoader.value = false;
            formDelete.reset();
        },
    });
};

const edit = (brand) => {
    inEdition.value = brand.id;
    form.name = brand.name;
    form.id = brand.id;
};

const submit = () => {
    form.post(route('brand-save'), {
        onSuccess: () => {
            form.reset();
            inEdition.value = 0;
        },
    });
};

const activate = (id) => {
    isLoader.value = true;
    form.put(route('brand-activate', id), {
        onFinish: () => {
            isLoader.value = false;
        },
    });
};

const deactivate = (id) => {
    isLoader.value = true;
    form.put(route('brand-deactivate', id), {
        onFinish: () => {
            isLoader.value = false;
        },
    });
};
</script>

<template>
    <AuthenticatedLayout>
        <Loader v-bind:show="isLoader"></Loader>

        <Head title="Marca" />
        <template #header>
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Marca</h1>
            </div>
        </template>
        <div class="row">
            <div class="col-lg-12">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="card mb-4 py-3 border-left-primary">
                            <div class="card-body">

                                <form @submit.prevent="submit">

                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <InputLabel for="name" value="Nome:" />
                                                <TextInput type="text" class="form-control" v-model="form.name" required
                                                    autofocus autocomplete="name" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.name" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="flex items-center justify-end mt-4 rigth">
                                        <PrimaryButton css-class="btn btn-primary float-right m-1"
                                            :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                            <span v-if="form.processing" class="spinner-border spinner-border-sm"
                                                role="status" aria-hidden="true"></span>
                                            Salvar
                                        </PrimaryButton>
                                        <PrimaryButton v-if="inEdition > 0" css-class="btn btn-info float-right m-1"
                                            v-on:click="form.reset(); inEdition = 0;"
                                            :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                            Novo
                                        </PrimaryButton>
                                    </div>

                                </form>
                            </div>
                        </div>

                    </div>

                    <div class="col-lg-12">
                        <div class="card mb-4 py-3 border-left-secondary">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Nome</th>
                                                <th scope="col">Ações</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr v-for="(brand, index) in brands"
                                                :class="{ 'table-info': inEdition == brand.id }">
                                                <th scope="row">{{ brand.id }}</th>
                                                <td>{{ brand.name }}</td>
                                                <td>
                                                    <button class="btn btn-info btn-icon-split mr-2"
                                                        v-on:click="edit(brand)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-edit"></i>
                                                        </span>
                                                        <span class="text">Editar</span>
                                                    </button>

                                                    <Modal :key="index" :modal-title="'Confirmar Exclusão de ' + brand.name"
                                                        :ok-botton-callback="deleteBrand"
                                                        :ok-botton-callback-param="brand.id"
                                                        btn-class="btn btn-danger btn-icon-split">
                                                        <template v-slot:button>
                                                            <span class="icon text-white-50">
                                                                <i class="fas fa-trash"></i>
                                                            </span>
                                                            <span class="text">Excluir</span>
                                                        </template>
                                                        <template v-slot:content>
                                                            Tem certeza que deseja apagar esse registro?
                                                        </template>
                                                    </Modal>

                                                    <button v-if="!brand.active" class="btn btn-success btn-icon-split mr-2"
                                                        v-on:click="activate(brand.id)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-check"></i>
                                                        </span>
                                                        <span class="text">Ativar</span>
                                                    </button>

                                                    <button v-if="brand.active" class="btn btn-warning btn-icon-split mr-2"
                                                        v-on:click="deactivate(brand.id)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-ban"></i>
                                                        </span>
                                                        <span class="text">Inativar</span>
                                                    </button>

                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </AuthenticatedLayout>
</template>
