// frontend/src/app/pages/broker/broker.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { Subject } from 'rxjs';
import { debounceTime, distinctUntilChanged, switchMap, finalize } from 'rxjs/operators';

import { BrokerService, Broker, BrokerCreateUpdateRequest } from '../../services/broker.service';
import { CityService, City } from '../../services/city.service';
import { ToastService } from '../../services/toast.service';
import { AuthenticatedLayoutComponent } from "../../shared/layouts/authenticated-layout/authenticated-layout.component";
import { ConfirmModalComponent } from "../../shared/components/confirm-modal/confirm-modal.component";
import { DatatableComponent } from "../../shared/components/datatable/datatable.component";
import { AutocompleteComponent } from "../../shared/components/autocomplete/autocomplete.component";
import { NgxMaskDirective } from 'ngx-mask';

@Component({
  selector: 'app-broker',
  standalone: true,
  imports: [CommonModule, FormsModule, AuthenticatedLayoutComponent, ConfirmModalComponent, DatatableComponent, AutocompleteComponent, NgxMaskDirective],
  templateUrl: './broker.component.html',
  styleUrls: ['./broker.component.scss']
})
export class BrokerComponent implements OnInit {
  private readonly brokerService: BrokerService = inject(BrokerService);
  private readonly cityService: CityService = inject(CityService);
  private readonly toastService: ToastService = inject(ToastService);

  brokers: Broker[] = [];
  inEdition: number = 0;
  isLoader: boolean = false;
  processing: boolean = false;
  errors: any = {};

  // Pagination and Filtering state
  pagination: any = {
    current_page: 1,
    per_page: 10,
    total: 0,
    last_page: 1,
    from: 0,
    to: 0
  };
  searchQuery: string = '';
  sortColumn: string = 'id';
  sortDirection: string = 'desc';

  selectedCityName: string = '';

  // Autocomplete Functions
  searchCities = (term: string) => this.cityService.searchCities(term);
  displayCity = (city: any) => city ? `${city.name} - ${city.states ? city.states : city.country}` : '';

  form = {
    id: 0,
    name: '',
    city_id: 0,
    contact: '',
    phone: '',
    email: '',
    national: false
  };

  ngOnInit(): void {
    this.loadBrokers();
  }

  loadBrokers(): void {
    this.isLoader = true;
    const params = {
      page: this.pagination.current_page,
      per_page: this.pagination.per_page,
      search: this.searchQuery,
      sort_column: this.sortColumn,
      sort_direction: this.sortDirection
    };

    this.brokerService.getBrokers(params).subscribe({
      next: (response: any) => {
        this.brokers = response.data || [];
        this.pagination = {
          current_page: response.current_page,
          per_page: response.per_page,
          total: response.total,
          last_page: response.last_page,
          from: response.from,
          to: response.to
        };
        this.isLoader = false;
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao carregar brokers');
        console.error('Erro ao carregar brokers:', error);
      }
    });
  }

  onSearch(query: string): void {
    this.searchQuery = query;
    this.pagination.current_page = 1;
    this.loadBrokers();
  }

  onPageChange(page: number): void {
    this.pagination.current_page = page;
    this.loadBrokers();
  }

  onPerPageChange(perPage: number): void {
    this.pagination.per_page = perPage;
    this.pagination.current_page = 1;
    this.loadBrokers();
  }

  sortBy(column: string): void {
    if (this.sortColumn === column) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortColumn = column;
      this.sortDirection = 'asc';
    }
    this.loadBrokers();
  }

  edit(broker: Broker): void {
    this.inEdition = broker.id;
    this.form = {
      id: broker.id,
      name: broker.name,
      city_id: broker.city_id,
      contact: broker.contact,
      phone: broker.phone,
      email: broker.email,
      national: broker.national
    };
    
    // Set initial city name for the autocomplete input
    this.selectedCityName = broker.city ? `${broker.city.name} - ${broker.city.states ? broker.city.states : broker.city.country}` : '';
    this.errors = {};
  }

  cancelEdit(): void {
    this.inEdition = 0;
    this.resetForm();
  }

  resetForm(): void {
    this.form = {
      id: 0,
      name: '',
      city_id: 0,
      contact: '',
      phone: '',
      email: '',
      national: false
    };
    this.selectedCityName = '';
    this.errors = {};
    this.inEdition = 0;
  }



  private validateForm(): boolean {
    this.errors = {};

    if (!this.form.name || this.form.name.trim() === '') {
      this.errors.name = ['O nome é obrigatório'];
    }
    
    if (!this.form.contact || this.form.contact.trim() === '') {
      this.errors.contact = ['O contato é obrigatório'];
    }

    if (!this.form.phone || this.form.phone.trim() === '') {
      this.errors.phone = ['O telefone é obrigatório'];
    }

    if (!this.form.email || this.form.email.trim() === '') {
      this.errors.email = ['O e-mail é obrigatório'];
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.form.email)) {
      this.errors.email = ['O e-mail informado não é válido'];
    }

    if (!this.form.city_id || this.form.city_id <= 0) {
      this.errors.city_id = ['O município é obrigatório. Selecione um município da lista.'];
    }

    return Object.keys(this.errors).length === 0;
  }

  submit(): void {
    if (!this.validateForm()) {
      return;
    }

    this.processing = true;

    const data: BrokerCreateUpdateRequest = {
      id: this.form.id,
      name: this.form.name,
      city_id: this.form.city_id,
      contact: this.form.contact,
      phone: this.form.phone,
      email: this.form.email,
      national: this.form.national
    };

    this.brokerService.saveBroker(data).subscribe({
      next: (response: any) => {
        this.processing = false;
        this.toastService.success(response.message || 'Broker salvo com sucesso');
        this.resetForm();
        this.loadBrokers();
      },
      error: (error: HttpErrorResponse) => {
        this.processing = false;
        if (error.status === 422) {
          this.errors = error.error.errors || {};
        } else {
          this.toastService.error('Erro ao salvar broker');
        }
        console.error('Erro ao salvar broker:', error);
      }
    });
  }

  deleteBroker(brokerId: number): void {
    this.isLoader = true;
    this.brokerService.deleteBroker(brokerId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Broker apagado com sucesso');
        this.loadBrokers();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao apagar broker');
        console.error('Erro ao deletar broker:', error);
      }
    });
  }

  activateBroker(brokerId: number): void {
    this.isLoader = true;
    this.brokerService.activateBroker(brokerId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Broker ativado com sucesso');
        this.loadBrokers();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao ativar broker');
        console.error('Erro ao ativar broker:', error);
      }
    });
  }

  deactivateBroker(brokerId: number): void {
    this.isLoader = true;
    this.brokerService.deactivateBroker(brokerId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Broker inativado com sucesso');
        this.loadBrokers();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao inativar broker');
        console.error('Erro ao inativar broker:', error);
      }
    });
  }

  isBrokerInEdition(brokerId: number): boolean {
    return this.inEdition === brokerId;
  }
}

<app-authenticated-layout title="Broker">
    <ng-container header>
        <div class="d-sm-flex align-items-center justify-content-between mb-4 animate-in">
            <h1 class="h3 mb-0 text-gray-800">Gerenciamento de Broker</h1>
        </div>
    </ng-container>

    <div class="row position-relative">
        <!-- Form Section -->
        <div class="col-lg-12 animate-in" style="animation-delay: 0.1s;">
            <div class="card mb-4 border-left-primary">
                <div class="card-body">
                    <h5 class="card-title mb-4 text-primary font-weight-bold">
                        <i class="fas fa-edit me-2"></i>{{ inEdition > 0 ? 'Editar Broker' : 'Cadastrar Novo Broker' }}
                    </h5>
                    <form (ngSubmit)="submit()">
                        <div class="row align-items-start">
                            
                            <!-- Nome -->
                            <div class="col-lg-4 mb-3">
                                <div class="form-group mb-0">
                                    <label for="name" class="form-label">Nome:</label>
                                    <input 
                                        type="text" 
                                        id="name" 
                                        class="form-control" 
                                        [(ngModel)]="form.name" 
                                        name="name" 
                                        placeholder="Ex: Broker"
                                        required 
                                        autofocus>
                                    
                                    <div *ngIf="errors['name']" class="text-danger mt-1">
                                        <small *ngFor="let err of errors['name']" class="d-block">{{ err }}</small>
                                    </div>
                                </div>
                            </div>

                            <!-- Município (Autocomplete) -->
                            <div class="col-lg-4 mb-3">
                                <app-autocomplete
                                    id="city"
                                    label="Cidade"
                                    placeholder="Digite para buscar a cidade..."
                                    [required]="true"
                                    [searchFn]="searchCities"
                                    [displayFn]="displayCity"
                                    valueField="id"
                                    [initialText]="selectedCityName"
                                    [(ngModel)]="form.city_id"
                                    name="city"
                                    [errors]="errors['city_id']">
                                </app-autocomplete>
                            </div>

                            <!-- Contato -->
                            <div class="col-lg-4 mb-3">
                                <div class="form-group mb-0">
                                    <label for="contact" class="form-label">Contato:</label>
                                    <input 
                                        type="text" 
                                        id="contact" 
                                        class="form-control" 
                                        [(ngModel)]="form.contact" 
                                        name="contact" 
                                        placeholder="Ex: João Silva"
                                        required>
                                    
                                    <div *ngIf="errors['contact']" class="text-danger mt-1">
                                        <small *ngFor="let err of errors['contact']" class="d-block">{{ err }}</small>
                                    </div>
                                </div>
                            </div>

                            <!-- Telefone -->
                            <div class="col-lg-4 mb-3">
                                <div class="form-group mb-0">
                                    <label for="phone" class="form-label">Telefone:</label>
                                    <input 
                                        type="text" 
                                        id="phone" 
                                        class="form-control" 
                                        [(ngModel)]="form.phone" 
                                        name="phone" 
                                        placeholder="Ex: (11) 99999-9999"
                                        mask="(00) 0000-00009"
                                        [dropSpecialCharacters]="false"
                                        required>
                                    
                                    <div *ngIf="errors['phone']" class="text-danger mt-1">
                                        <small *ngFor="let err of errors['phone']" class="d-block">{{ err }}</small>
                                    </div>
                                </div>
                            </div>

                            <!-- E-mail -->
                            <div class="col-lg-4 mb-3">
                                <div class="form-group mb-0">
                                    <label for="email" class="form-label">E-mail:</label>
                                    <input 
                                        type="email" 
                                        id="email" 
                                        class="form-control" 
                                        [(ngModel)]="form.email" 
                                        name="email" 
                                        placeholder="exemplo@email.com"
                                        required>
                                    
                                    <div *ngIf="errors['email']" class="text-danger mt-1">
                                        <small *ngFor="let err of errors['email']" class="d-block">{{ err }}</small>
                                    </div>
                                </div>
                            </div>

                            <!-- Nacional Radios -->
                            <div class="col-lg-4 mb-3">
                                <div class="form-group mb-0">
                                    <label class="form-label"> </label>
                                    <div class="card">
                                        <div class="card-body py-2">
                                            <div class="form-check">
                                                <input class="form-check-input" type="radio" id="nationalTrue" [value]="true" [(ngModel)]="form.national" name="national">
                                                <label class="form-check-label" for="nationalTrue">
                                                    Broker Nacional
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="radio" id="nationalFalse" [value]="false" [(ngModel)]="form.national" name="national">
                                                <label class="form-check-label" for="nationalFalse">
                                                    Broker Internacional
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Botões -->
                        <div class="row mt-3">
                            <div class="col-12 d-flex justify-content-end">
                                <button 
                                    type="button" 
                                    *ngIf="inEdition > 0" 
                                    class="btn btn-outline-secondary me-2" 
                                    (click)="resetForm()"
                                    [disabled]="processing">
                                    <i class="fas fa-plus me-1"></i> Novo
                                </button>

                                <button 
                                    type="submit" 
                                    class="btn btn-primary shadow-sm" 
                                    [disabled]="processing" 
                                    [class.opacity-50]="processing">
                                    <span *ngIf="processing" class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
                                    <i *ngIf="!processing" class="fas fa-save me-1"></i>
                                    Salvar
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>

        <!-- Table Section -->
        <div class="col-lg-12 animate-in" style="animation-delay: 0.2s;">
            <div class="card mb-4 border-left-secondary">
                <div class="card-body">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <h5 class="card-title mb-0 text-secondary font-weight-bold">
                            <i class="fas fa-list me-2"></i>Lista de Brokers
                        </h5>
                    </div>

                    <app-datatable 
                        [pagination]="pagination" 
                        [loading]="isLoader"
                        (search)="onSearch($event)"
                        (pageChange)="onPageChange($event)"
                        (perPageChange)="onPerPageChange($event)">
                        
                        <div class="table-responsive">
                            <table class="table table-hover" width="100%" cellspacing="0">
                                <thead class="table-light">
                                    <tr>
                                        <th scope="col" (click)="sortBy('id')" style="cursor: pointer; width: 80px;">
                                            <div class="d-flex align-items-center">
                                                ID <i class="fas fa-sort ms-2 text-muted" [ngClass]="{'fa-sort-up text-primary': sortColumn === 'id' && sortDirection === 'asc', 'fa-sort-down text-primary': sortColumn === 'id' && sortDirection === 'desc'}"></i>
                                            </div>
                                        </th>
                                        <th scope="col" (click)="sortBy('name')" style="cursor: pointer;">
                                            <div class="d-flex align-items-center">
                                                Nome <i class="fas fa-sort ms-2 text-muted" [ngClass]="{'fa-sort-up text-primary': sortColumn === 'name' && sortDirection === 'asc', 'fa-sort-down text-primary': sortColumn === 'name' && sortDirection === 'desc'}"></i>
                                            </div>
                                        </th>
                                        <th scope="col">Município</th>
                                        <th scope="col" (click)="sortBy('contact')" style="cursor: pointer;">
                                            <div class="d-flex align-items-center">
                                                Contato <i class="fas fa-sort ms-2 text-muted" [ngClass]="{'fa-sort-up text-primary': sortColumn === 'contact' && sortDirection === 'asc', 'fa-sort-down text-primary': sortColumn === 'contact' && sortDirection === 'desc'}"></i>
                                            </div>
                                        </th>
                                        <th scope="col" (click)="sortBy('phone')" style="cursor: pointer;">
                                            <div class="d-flex align-items-center">
                                                Telefone <i class="fas fa-sort ms-2 text-muted" [ngClass]="{'fa-sort-up text-primary': sortColumn === 'phone' && sortDirection === 'asc', 'fa-sort-down text-primary': sortColumn === 'phone' && sortDirection === 'desc'}"></i>
                                            </div>
                                        </th>
                                        <th scope="col" (click)="sortBy('email')" style="cursor: pointer;">
                                            <div class="d-flex align-items-center">
                                                E-mail <i class="fas fa-sort ms-2 text-muted" [ngClass]="{'fa-sort-up text-primary': sortColumn === 'email' && sortDirection === 'asc', 'fa-sort-down text-primary': sortColumn === 'email' && sortDirection === 'desc'}"></i>
                                            </div>
                                        </th>
                                        <th scope="col">Tipo</th>
                                        <th scope="col" class="text-end">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr *ngFor="let broker of brokers" [class.table-info]="isBrokerInEdition(broker.id)">
                                        <th scope="row" class="font-weight-bold">{{ broker.id }}</th>
                                        <td>
                                            <span [class.text-muted]="!broker.active">{{ broker.name }}</span>
                                            <span *ngIf="!broker.active" class="badge bg-light text-muted ms-2">Inativo</span>
                                        </td>
                                        <td>
                                            <span [class.text-muted]="!broker.active">{{ broker.city ? broker.city.name + ' - ' + (broker.city.states ? broker.city.states : broker.city.country) : '-' }}</span>
                                        </td>
                                        <td><span [class.text-muted]="!broker.active">{{ broker.contact }}</span></td>
                                        <td><span [class.text-muted]="!broker.active">{{ broker.phone }}</span></td>
                                        <td><span [class.text-muted]="!broker.active">{{ broker.email }}</span></td>
                                        <td><span [class.text-muted]="!broker.active">{{ broker.national ? 'Nacional' : 'Internacional' }}</span></td>
                                        <td class="text-end">
                                            <div class="d-flex justify-content-end gap-2 flex-wrap">
                                                <!-- Editar -->
                                                <button class="btn btn-sm btn-info text-white shadow-sm" (click)="edit(broker)" title="Editar">
                                                    <i class="fas fa-edit me-1"></i> Editar
                                                </button>

                                                <!-- Ativar/Inativar -->
                                                <button *ngIf="!broker.active" class="btn btn-sm btn-success shadow-sm" (click)="activateBroker(broker.id)" title="Ativar">
                                                    <i class="fas fa-check me-1"></i> Ativar
                                                </button>

                                                <app-confirm-modal 
                                                    *ngIf="broker.active"
                                                    [btnClass]="'btn btn-sm btn-warning shadow-sm'" 
                                                    [modalTitle]="'Inativar Broker'" 
                                                    [message]="'Tem certeza que deseja inativar o broker ' + broker.name + '?'"
                                                    [okButtonLabel]="'Confirmar'"
                                                    (confirm)="deactivateBroker(broker.id)">
                                                    <span modal-button><i class="fas fa-ban me-1"></i> Inativar</span>
                                                </app-confirm-modal>

                                                <!-- Deletar -->
                                                <app-confirm-modal 
                                                    [btnClass]="'btn btn-sm btn-danger shadow-sm'" 
                                                    [modalTitle]="'Excluir Broker'" 
                                                    [message]="'Ação irreversível! Deseja realmente excluir o broker ' + broker.name + '?'"
                                                    [okButtonLabel]="'Excluir'"
                                                    (confirm)="deleteBroker(broker.id)">
                                                    <span modal-button><i class="fas fa-trash me-1"></i> Excluir</span>
                                                </app-confirm-modal>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr *ngFor="let i of [1,2,3,4,5].slice(0, isLoader ? 5 : 0)">
                                        <td colspan="8" class="text-center py-3">
                                            <div class="placeholder-glow">
                                                <span class="placeholder col-12 rounded"></span>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr *ngIf="brokers.length === 0 && !isLoader">
                                        <td colspan="8" class="text-center py-5 text-muted">
                                            <i class="fas fa-folder-open fa-3x mb-3 d-block opacity-25"></i>
                                            Nenhum broker encontrado.
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </app-datatable>
                </div>
            </div>
        </div>
    </div>
</app-authenticated-layout>

// resources/js/Pages/Auth/Auxiliaries/Broker.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import Modal from '@/Components/Modal.vue';
import Loader from '@/Components/Loader.vue';
import { Head, useForm } from '@inertiajs/inertia-vue3';
import { onMounted, ref } from 'vue';


const props = defineProps({
    brokers: Array,
    cities: Array
});

const inEdition = ref(0);

const form = useForm({
    id: 0,
    name: '',
    city: '',
    contact: '',
    phone: '',
    email: '',
    national: false,
});

const formDelete = useForm({
    id: 0
});


onMounted(() => {
    $('#city').select2({
        theme: "bootstrap4",
        language: "pt-Br"
    }).on('select2:select', (e) => {
        form.city = e.params.data.id;
    });

    $('.phone').mask('(00) 00000-0000');
    $('table').DataTable({
        language: {
            url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/pt-BR.json',
        },
    });
});

const isLoader = ref(false);

const deleteBroker = (id) => {
    isLoader.value = true;
    formDelete.id = id;
    formDelete.delete(route('broker-delete'), {
        onFinish: () => {
            isLoader.value = false;
            formDelete.reset();
        },
    });
};

const edit = (broker) => {
    inEdition.value = broker.id;
    form.name = broker.name;
    form.id = broker.id;
    form.contact = broker.contact;
    form.phone = broker.phone;
    form.email = broker.email;
    form.national = broker.national == true || broker.national == 1;
    form.city = broker.city_id;

    $('#city').val(form.city).trigger('change');
    $('.phone').val(form.phone).trigger('keyup');
};

const newItem = (() => {
    form.reset();
    $('#city').val('').trigger('change');
    inEdition.value = 0;
});

const submit = () => {
    form.post(route('broker-save'), {
        onSuccess: () => {
            newItem();
            isLoader.value = false;
        },
    });
};


const activate = (id) => {
    isLoader.value = true;
    form.put(route('brokers-activate', id), {
        onFinish: () => {
            isLoader.value = false;
        },
    });
};

const deactivate = (id) => {
    isLoader.value = true;
    form.put(route('brokers-deactivate', id), {
        onFinish: () => {
            isLoader.value = false;
        },
    });
};

</script>

<template>
    <AuthenticatedLayout>
        <Loader v-bind:show="isLoader"></Loader>

        <Head title="Broker" />
        <template #header>
            <div class="d-sm-flex align-items-center justify-content-between">
                <h1 class="h3 mb-0 text-gray-800">Broker</h1>
            </div>
        </template>
        <div class="row">
            <div class="col-lg-12">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="card mb-4 py-3 border-left-primary">
                            <div class="card-body">

                                <form @submit.prevent="submit">

                                    <div class="row">
                                        <div class="col">
                                            <div class="form-group">
                                                <InputLabel for="name" value="Nome:" />
                                                <TextInput type="text" class="form-control" v-model="form.name" required
                                                    autofocus autocomplete="name" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.name" />
                                            </div>

                                        </div>
                                        <div class="col">
                                            <div class="form-group">
                                                <InputLabel for="city" value="Cidade:" />

                                                <select class="form-control" id="city" :required="required">
                                                    <option value="">.::Selecione::.</option>
                                                    <option v-for="(option, index) in cities" :value="option.id">
                                                        {{ option.name }} - {{ option.states ? option.states :
                                                            option.country }}
                                                    </option>

                                                </select>

                                                <InputError class="mt-2 text-danger" :message="form.errors.city" />
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="form-group">
                                                <InputLabel for="contact" value="Contato:" />
                                                <TextInput type="text" class="form-control" v-model="form.contact"
                                                    required autofocus autocomplete="contact" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.contact" />
                                            </div>

                                        </div>
                                        <div class="col">
                                            <div class="form-group">
                                                <InputLabel for="phone" value="Telefone:" />
                                                <TextInput id="phone" type="text" class="form-control phone"
                                                    v-model="form.phone" required autofocus autocomplete="phone" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.phone" />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">

                                        <div class="col-3">
                                            <div class="form-group">
                                                <InputLabel for="email" value="E-mail:" />
                                                <TextInput type="email" class="form-control" v-model="form.email"
                                                    required autofocus autocomplete="email" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.email" />
                                            </div>
                                        </div>

                                        <div class="col">
                                            <div class="form-group">
                                                <InputLabel for="national" value=" " />

                                                <div class="card">
                                                    <div class="card-body">
                                                        <div class="form-check">
                                                            <input class="form-check-input" v-model="form.national"
                                                                :value="true" type="radio" id="autoSizingCheck1">
                                                            <label class="form-check-label" for="autoSizingCheck1">
                                                                Broker Nacional
                                                            </label>
                                                        </div>
                                                        <div class="form-check">
                                                            <input class="form-check-input" v-model="form.national"
                                                                :value="false" type="radio" id="autoSizingCheck">
                                                            <label class="form-check-label" for="autoSizingCheck">
                                                                Broker Internacional
                                                            </label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="flex items-center justify-end mt-4 rigth">
                                        <PrimaryButton css-class="btn btn-primary float-right m-1"
                                            :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                            <span v-if="form.processing" class="spinner-border spinner-border-sm"
                                                role="status" aria-hidden="true"></span>
                                            Salvar
                                        </PrimaryButton>
                                        <PrimaryButton v-if="inEdition > 0" css-class="btn btn-info float-right m-1"
                                            v-on:click="form.reset(); inEdition = 0;"
                                            :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                            Novo
                                        </PrimaryButton>
                                    </div>

                                </form>
                            </div>
                        </div>

                    </div>

                    <div class="col-lg-12">
                        <div class="card mb-4 py-3 border-left-secondary">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Nome</th>
                                                <th scope="col">Cidade</th>
                                                <th scope="col">Contato</th>
                                                <th scope="col">Telefone</th>
                                                <th scope="col">E-mail</th>
                                                <th scope="col">Tipo</th>
                                                <th scope="col">Ações</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr v-for="(broker, index) in brokers"
                                                :class="{ 'table-info': inEdition == broker.id }">
                                                <th scope="row">{{ broker.id }}</th>
                                                <td>{{ broker.name }}</td>
                                                <td>{{ broker.city?.name }} - {{ broker.city?.states ?
                                                    broker.city.states :
                                                    broker.city?.country }}</td>
                                                <td>{{ broker.contact }}</td>
                                                <td class="phone">{{ broker.phone }}</td>
                                                <td>{{ broker.email }}</td>
                                                <td>{{ broker.national ? "Nacional" : "Internacional" }}</td>
                                                <td>
                                                    <button class="btn btn-sm btn-info btn-icon-split mr-2"
                                                        v-on:click="edit(broker)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-edit"></i>
                                                        </span>
                                                        <span class="text">Editar</span>
                                                    </button>

                                                    <Modal :key="index"
                                                        :modal-title="'Confirmar Exclusão de ' + broker.name"
                                                        :ok-botton-callback="deleteBroker"
                                                        :ok-botton-callback-param="broker.id"
                                                        btn-class="btn  btn-sm btn-danger btn-icon-split mr-2">
                                                        <template v-slot:button>
                                                            <span class="icon text-white-50">
                                                                <i class="fas fa-trash"></i>
                                                            </span>
                                                            <span class="text">Excluir</span>
                                                        </template>
                                                        <template v-slot:content>
                                                            Tem certeza que deseja apagar esse registro?
                                                        </template>
                                                    </Modal>


                                                    <button v-if="!broker.active"
                                                        class="btn btn-sm btn-success btn-icon-split mr-2"
                                                        v-on:click="activate(broker.id)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-check"></i>
                                                        </span>
                                                        <span class="text">Ativar</span>
                                                    </button>

                                                    <button v-if="broker.active"
                                                        class="btn btn-sm btn-warning btn-icon-split mr-2"
                                                        v-on:click="deactivate(broker.id)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-ban"></i>
                                                        </span>
                                                        <span class="text">Inativar</span>
                                                    </button>

                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </AuthenticatedLayout>
</template>
