// frontend/src/app/pages/hotel/hotel/hotel.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ProviderService, Provider, ProviderCreateUpdateRequest } from '../../../services/provider.service';
import { CityService, City } from '../../../services/city.service';
import { AuthenticatedLayoutComponent } from '../../../shared/layouts/authenticated-layout/authenticated-layout.component';
import { DatatableComponent } from '../../../shared/components/datatable/datatable.component';
import { ConfirmModalComponent } from '../../../shared/components/confirm-modal/confirm-modal.component';
import { ModalComponent } from '../../../shared/components/modal/modal.component';
import { ToastService } from '../../../services/toast.service';
import { AutocompleteComponent } from '../../../shared/components/autocomplete/autocomplete.component';
import { NgxMaskDirective, provideNgxMask } from 'ngx-mask';

@Component({
  selector: 'app-hotel',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    AuthenticatedLayoutComponent,
    DatatableComponent,
    ConfirmModalComponent,
    ModalComponent,
    AutocompleteComponent,
    NgxMaskDirective,
  ],
  providers: [provideNgxMask()],
  templateUrl: './hotel.component.html',
  styleUrls: ['./hotel.component.scss'],
})
export class HotelComponent implements OnInit {
  private readonly providerService = inject(ProviderService);
  private readonly cityService = inject(CityService);
  private readonly toastr = inject(ToastService);

  providers: Provider[] = [];
  isLoader = false;
  processing = false;
  inEdition = 0;
  showModal = false;

  pagination = {
    current_page: 1,
    per_page: 10,
    total: 0,
    last_page: 1,
    from: 0,
    to: 0,
  };

  searchTerm = '';
  sortColumn = 'id';
  sortDirection = 'desc';

  form: ProviderCreateUpdateRequest = this.getEmptyForm();
  errors: any = {};
  selectedCityName = '';

  ngOnInit(): void {
    this.loadProviders();
  }

  validatePercent(event: any): void {
    const input = event.target as HTMLInputElement;
    const name = input.name;
    let val = parseFloat(input.value);
    if (isNaN(val) || val < 0) {
      val = 0;
    } else if (val > 100) {
      val = 100;
    }
    // round to one decimal place
    val = Math.round(val * 10) / 10;
    // Update form model
    (this.form as any)[name] = val;
    // Reflect corrected value in input
    input.value = val.toString();
  }

  getEmptyForm(): ProviderCreateUpdateRequest {
    return {
      id: 0,
      name: '',
      city_id: 0,
      contact: '',
      phone: '',
      email: '',
      national: true,
      iss_percent: 0,
      service_percent: 0,
      iva_percent: 0,
      payment_method: '',
      checkin_time: '',
      checkin_time_end: '',
      checkout_time: '',
      checkout_time_end: '',
      has_hotel: true,
      type: 'hotel',
    };
  }

  loadProviders(): void {
    this.isLoader = true;
    const params = {
      page: this.pagination.current_page,
      per_page: this.pagination.per_page,
      search: this.searchTerm,
      sort_column: this.sortColumn,
      sort_direction: this.sortDirection,
      is_hotel: 1,
    };

    this.providerService.getProviders(params).subscribe({
      next: (response) => {
        this.providers = response.data;
        this.pagination.current_page = response.current_page;
        this.pagination.total = response.total;
        this.pagination.per_page = response.per_page;
        this.pagination.last_page = response.last_page;
        this.pagination.from = response.from;
        this.pagination.to = response.to;
        this.isLoader = false;
      },
      error: () => {
        this.toastr.error('Erro ao carregar hotéis.');
        this.isLoader = false;
      },
    });
  }

  onSearch(term: string): void {
    this.searchTerm = term;
    this.pagination.current_page = 1;
    this.loadProviders();
  }

  onPageChange(page: number): void {
    this.pagination.current_page = page;
    this.loadProviders();
  }

  onPerPageChange(perPage: number): void {
    this.pagination.per_page = perPage;
    this.pagination.current_page = 1;
    this.loadProviders();
  }

  sortBy(column: string): void {
    if (this.sortColumn === column) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortColumn = column;
      this.sortDirection = 'asc';
    }
    this.loadProviders();
  }

  openModal(): void {
    this.resetForm();
    this.showModal = true;
  }

  closeModal(): void {
    this.showModal = false;
    this.resetForm();
  }

  edit(provider: Provider): void {
    this.inEdition = provider.id;
    this.form = {
      id: provider.id,
      name: provider.name,
      city_id: provider.city_id,
      contact: provider.contact || '',
      phone: provider.phone || '',
      email: provider.email || '',
      national: String(provider.national) === '1' || String(provider.national) === 'true',
      iss_percent: provider.iss_percent || 0,
      service_percent: provider.service_percent || 0,
      iva_percent: provider.iva_percent || 0,
      payment_method: provider.payment_method || '',
      checkin_time: provider.checkin_time || '',
      checkin_time_end: provider.checkin_time_end || '',
      checkout_time: provider.checkout_time || '',
      checkout_time_end: provider.checkout_time_end || '',
      has_hotel: true,
      type: 'hotel',
    };

    this.selectedCityName = provider.city
      ? `${provider.city.name} - ${provider.city.states ? provider.city.states : provider.city.country}`
      : '';
    this.errors = {};
    this.showModal = true;
  }

  cancelEdit(): void {
    this.closeModal();
  }

  resetForm(): void {
    this.form = this.getEmptyForm();
    this.selectedCityName = '';
    this.errors = {};
    this.inEdition = 0;
  }

  isProviderInEdition(id: number): boolean {
    return this.inEdition === id;
  }

  private validateForm(): boolean {
    this.errors = {};

    if (!this.form.name || this.form.name.trim() === '') {
      this.errors['name'] = ['O nome é obrigatório'];
    }

    if (!this.form.city_id || this.form.city_id <= 0) {
      this.errors['city_id'] = ['A cidade é obrigatória. Selecione uma cidade da lista.'];
    }

    return Object.keys(this.errors).length === 0;
  }

  submit(): void {
    if (!this.validateForm()) {
      this.toastr.warning('Verifique os campos do formulário.');
      return;
    }

    this.processing = true;
    this.errors = {};

    // Enforce max 100 with at most 1 decimal place on percentages
    const percentFields: ('iss_percent' | 'service_percent' | 'iva_percent')[] = ['iss_percent', 'service_percent', 'iva_percent'];
    percentFields.forEach((field) => {
      if (this.form[field] !== undefined && this.form[field] !== null) {
        let val = Number(this.form[field]);
        if (isNaN(val) || val < 0) {
          this.form[field] = 0;
        } else {
          if (val > 100) {
            val = 100;
          }
          // Round to at most 1 decimal place
          this.form[field] = Math.round(val * 10) / 10;
        }
      }
    });

    this.providerService.saveProvider(this.form).subscribe({
      next: (res) => {
        this.toastr.success(res.message || 'Hotel salvo com sucesso!');
        this.closeModal();
        this.loadProviders();
        this.processing = false;
      },
      error: (err) => {
        if (err.status === 422) {
          this.errors = err.error.errors;
          this.toastr.warning('Verifique os campos do formulário.');
        } else {
          this.toastr.error('Erro ao salvar o hotel.');
        }
        this.processing = false;
      },
    });
  }

  deleteProvider(id: number): void {
    this.providerService.deleteProvider(id).subscribe({
      next: (res) => {
        this.toastr.success(res.message || 'Hotel excluído com sucesso!');
        this.loadProviders();
      },
      error: () => {
        this.toastr.error('Erro ao excluir o hotel.');
      },
    });
  }

  activateProvider(id: number): void {
    this.providerService.activateProvider(id).subscribe({
      next: (res) => {
        this.toastr.success(res.message || 'Hotel ativado com sucesso!');
        this.loadProviders();
      },
      error: () => {
        this.toastr.error('Erro ao ativar o hotel.');
      },
    });
  }

  deactivateProvider(id: number): void {
    this.providerService.deactivateProvider(id).subscribe({
      next: (res) => {
        this.toastr.success(res.message || 'Hotel inativado com sucesso!');
        this.loadProviders();
      },
      error: () => {
        this.toastr.error('Erro ao inativar o hotel.');
      },
    });
  }

  searchCities = (term: string) => {
    return this.cityService.searchCities(term);
  };

  displayCity = (city: City) => {
    return `${city.name} - ${city.states ? city.states : city.country}`;
  };
}

<app-authenticated-layout title="Hotéis (Fornecedores)">
  <ng-container header>
    <div class="d-sm-flex align-items-center justify-content-between mb-4 animate-in">
      <h1 class="h3 mb-0 text-gray-800">Gerenciamento de Hotéis</h1>
    </div>
  </ng-container>

  <div class="row position-relative">
    <!-- Modal de Cadastro/Edição -->
    <app-modal [show]="showModal" (close)="closeModal()" [title]="inEdition > 0 ? 'Editar Hotel' : 'Cadastrar Novo Hotel'" icon="fa-edit" size="lg">
      <form (ngSubmit)="submit()">
        <div class="row align-items-start">
          <!-- Nome -->
          <div class="col-lg-6 mb-3">
            <div class="form-group mb-0">
              <label for="name" class="form-label">
                Nome:
                <span class="text-danger">*</span>
              </label>
              <input
                type="text"
                id="name"
                class="form-control"
                [class.is-invalid]="errors['name']"
                [(ngModel)]="form.name"
                name="name"
                placeholder="Ex: Hotel Plaza"
                required
                autofocus />

              <div *ngIf="errors['name']" class="text-danger mt-1">
                <small *ngFor="let err of errors['name']" class="d-block">{{ err }}</small>
              </div>
            </div>
          </div>

          <!-- Cidade (Autocomplete) -->
          <div class="col-lg-6 mb-3">
            <app-autocomplete
              id="city"
              label="Cidade"
              placeholder="Digite para buscar a cidade..."
              [required]="true"
              [searchFn]="searchCities"
              [displayFn]="displayCity"
              valueField="id"
              [initialText]="selectedCityName"
              [(ngModel)]="form.city_id"
              name="city"
              [errors]="errors['city_id']"></app-autocomplete>
          </div>

          <!-- E-mail -->
          <div class="col-lg-6 mb-3">
            <div class="form-group mb-0">
              <label for="email" class="form-label">E-mail:</label>
              <input
                type="email"
                id="email"
                class="form-control"
                [class.is-invalid]="errors['email']"
                [(ngModel)]="form.email"
                name="email"
                placeholder="exemplo@email.com" />

              <div *ngIf="errors['email']" class="text-danger mt-1">
                <small *ngFor="let err of errors['email']" class="d-block">{{ err }}</small>
              </div>
            </div>
          </div>

          <!-- Contato -->
          <div class="col-lg-6 mb-3">
            <div class="form-group mb-0">
              <label for="contact" class="form-label">Contato:</label>
              <input
                type="text"
                id="contact"
                class="form-control"
                [class.is-invalid]="errors['contact']"
                [(ngModel)]="form.contact"
                name="contact"
                placeholder="Ex: João Silva" />

              <div *ngIf="errors['contact']" class="text-danger mt-1">
                <small *ngFor="let err of errors['contact']" class="d-block">{{ err }}</small>
              </div>
            </div>
          </div>

          <!-- Telefone -->
          <div class="col-lg-6 mb-3">
            <div class="form-group mb-0">
              <label for="phone" class="form-label">Telefone:</label>
              <input
                type="text"
                id="phone"
                class="form-control"
                [class.is-invalid]="errors['phone']"
                [(ngModel)]="form.phone"
                name="phone"
                placeholder="Ex: (11) 99999-9999"
                mask="(00) 0000-00009"
                [dropSpecialCharacters]="false" />

              <div *ngIf="errors['phone']" class="text-danger mt-1">
                <small *ngFor="let err of errors['phone']" class="d-block">{{ err }}</small>
              </div>
            </div>
          </div>

          <!-- Forma de Pagamento -->
          <div class="col-lg-6 mb-3">
            <div class="form-group mb-0">
              <label for="payment_method" class="form-label">Forma de Pagamento:</label>
              <select
                id="payment_method"
                class="form-select"
                [class.is-invalid]="errors['payment_method']"
                [(ngModel)]="form.payment_method"
                name="payment_method">
                <option value="" disabled selected>Selecione...</option>
                <option value="Indefinido">Indefinido</option>
                <option value="Dinheiro">Dinheiro</option>
                <option value="Cartão">Cartão</option>
              </select>

              <div *ngIf="errors['payment_method']" class="text-danger mt-1">
                <small *ngFor="let err of errors['payment_method']" class="d-block">{{ err }}</small>
              </div>
            </div>
          </div>

          <!-- Taxas (%) -->
          <div class="col-lg-6 mb-3">
            <div class="form-group mb-0">
              <label class="form-label fw-bold">Taxas (%)</label>
              <div class="row g-2">
                <div class="col-4">
                  <small class="text-muted d-block mb-1">ISS</small>
                  <input
                    type="number"
                    class="form-control text-start"
                    [(ngModel)]="form.iss_percent"
                    name="iss_percent"
                    min="0"
                    max="100"
                    step="0.1"
                    (input)="validatePercent($event)" />
                </div>
                <div class="col-4">
                  <small class="text-muted d-block mb-1">Serviço</small>
                  <input
                    type="number"
                    class="form-control text-start"
                    [(ngModel)]="form.service_percent"
                    name="service_percent"
                    min="0"
                    max="100"
                    step="0.1"
                    (input)="validatePercent($event)" />
                </div>
                <div class="col-4">
                  <small class="text-muted d-block mb-1">IVA</small>
                  <input
                    type="number"
                    class="form-control text-start"
                    [(ngModel)]="form.iva_percent"
                    name="iva_percent"
                    min="0"
                    max="100"
                    step="0.1"
                    (input)="validatePercent($event)" />
                </div>
              </div>
            </div>
          </div>

          <!-- Nacional Switch -->
          <div class="col-lg-6 mb-3">
            <label class="form-label d-block fw-bold">Nacional?</label>
            <div class="form-switch mt-2">
              <input class="form-check-input cursor-pointer" type="checkbox" id="national" [(ngModel)]="form.national" name="national" />
              <label class="form-check-label cursor-pointer text-muted ms-2" for="national">{{ form.national ? 'Sim' : 'Não' }}</label>
            </div>
          </div>

          <!-- Check-in -->
          <div class="col-lg-6 mb-3">
            <div class="form-group mb-0">
              <label class="form-label fw-bold">Check-in</label>
              <div class="row align-items-center g-2">
                <div class="col-6">
                  <small class="text-muted d-block">Início</small>
                  <input type="time" class="form-control" [(ngModel)]="form.checkin_time" name="checkin_time" />
                </div>
                <div class="col-6">
                  <small class="text-muted d-block">Fim</small>
                  <input type="time" class="form-control" [(ngModel)]="form.checkin_time_end" name="checkin_time_end" />
                </div>
              </div>
            </div>
          </div>

          <!-- Check-out -->
          <div class="col-lg-6 mb-3">
            <div class="form-group mb-0">
              <label class="form-label fw-bold">Check-out</label>
              <div class="row align-items-center g-2">
                <div class="col-6">
                  <small class="text-muted d-block">Início</small>
                  <input type="time" class="form-control" [(ngModel)]="form.checkout_time" name="checkout_time" />
                </div>
                <div class="col-6">
                  <small class="text-muted d-block">Fim</small>
                  <input type="time" class="form-control" [(ngModel)]="form.checkout_time_end" name="checkout_time_end" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer px-0 pb-0 pt-3 d-flex justify-content-end gap-2 border-top">
          <button type="button" class="btn btn-outline-secondary" (click)="closeModal()" [disabled]="processing">
            <i class="fas fa-times me-1"></i>
            Cancelar
          </button>
          <button type="submit" class="btn btn-primary shadow-sm" [disabled]="processing">
            <span *ngIf="processing" class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
            <i *ngIf="!processing" class="fas fa-save me-1"></i>
            Salvar
          </button>
        </div>
      </form>
    </app-modal>

    <!-- Table Section -->
    <div class="col-lg-12 animate-in" style="animation-delay: 0.2s">
      <div class="card mb-4 border-left-secondary">
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between mb-4">
            <h5 class="card-title mb-0 text-secondary font-weight-bold">
              <i class="fas fa-list me-2"></i>
              Lista de Hotéis
            </h5>
            <button class="btn btn-primary btn-sm shadow-sm" (click)="openModal()" [disabled]="processing">
              <i class="fas fa-plus me-1"></i>
              Novo Hotel
            </button>
          </div>

          <app-datatable
            [pagination]="pagination"
            [loading]="isLoader"
            (search)="onSearch($event)"
            (pageChange)="onPageChange($event)"
            (perPageChange)="onPerPageChange($event)">
            <div class="table-responsive">
              <table class="table table-hover" width="100%" cellspacing="0">
                <thead class="table-light">
                  <tr>
                    <th scope="col" (click)="sortBy('id')" style="cursor: pointer; width: 80px">
                      <div class="d-flex align-items-center">
                        ID
                        <i
                          class="fas fa-sort ms-2 text-muted"
                          [ngClass]="{
                            'fa-sort-up text-primary': sortColumn === 'id' && sortDirection === 'asc',
                            'fa-sort-down text-primary': sortColumn === 'id' && sortDirection === 'desc',
                          }"></i>
                      </div>
                    </th>
                    <th scope="col" (click)="sortBy('name')" style="cursor: pointer">
                      <div class="d-flex align-items-center">
                        Nome
                        <i
                          class="fas fa-sort ms-2 text-muted"
                          [ngClass]="{
                            'fa-sort-up text-primary': sortColumn === 'name' && sortDirection === 'asc',
                            'fa-sort-down text-primary': sortColumn === 'name' && sortDirection === 'desc',
                          }"></i>
                      </div>
                    </th>
                    <th scope="col">Cidade</th>
                    <th scope="col" (click)="sortBy('email')" style="cursor: pointer">
                      <div class="d-flex align-items-center">
                        E-mail
                        <i
                          class="fas fa-sort ms-2 text-muted"
                          [ngClass]="{
                            'fa-sort-up text-primary': sortColumn === 'email' && sortDirection === 'asc',
                            'fa-sort-down text-primary': sortColumn === 'email' && sortDirection === 'desc',
                          }"></i>
                      </div>
                    </th>
                    <th scope="col">Tipo</th>
                    <th scope="col" class="text-end">Ações</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let provider of providers" [class.table-info]="isProviderInEdition(provider.id)">
                    <th scope="row" class="font-weight-bold">{{ provider.id }}</th>
                    <td>
                      <span [class.text-muted]="!provider.active">{{ provider.name }}</span>
                      <span *ngIf="!provider.active" class="badge bg-light text-muted ms-2">Inativo</span>
                    </td>
                    <td>
                      <span [class.text-muted]="!provider.active">
                        {{ provider.city ? provider.city.name + ' - ' + (provider.city.states ? provider.city.states : provider.city.country) : '-' }}
                      </span>
                    </td>
                    <td>
                      <span [class.text-muted]="!provider.active">{{ provider.email }}</span>
                    </td>
                    <td>
                      <span [class.text-muted]="!provider.active">
                        {{ provider.national ? 'Nacional' : 'Internacional' }}
                      </span>
                    </td>
                    <td class="text-end">
                      <div class="d-flex justify-content-end gap-2 flex-wrap">
                        <!-- Editar -->
                        <button class="btn btn-info text-white shadow-sm btn-action" (click)="edit(provider)" data-tooltip="Editar Hotel">
                          <i class="fas fa-edit"></i>
                        </button>

                        <!-- Ativar/Inativar -->
                        <button
                          *ngIf="!provider.active"
                          class="btn btn-success shadow-sm btn-action"
                          (click)="activateProvider(provider.id)"
                          data-tooltip="Ativar Hotel">
                          <i class="fas fa-check"></i>
                        </button>

                        <app-confirm-modal
                          *ngIf="provider.active"
                          [btnClass]="'btn btn-warning shadow-sm btn-action'"
                          [modalTitle]="'Inativar Hotel'"
                          [message]="'Tem certeza que deseja inativar o hotel ' + provider.name + '?'"
                          [okButtonLabel]="'Confirmar'"
                          [tooltip]="'Inativar Hotel'"
                          (confirm)="deactivateProvider(provider.id)">
                          <span modal-button><i class="fas fa-ban"></i></span>
                        </app-confirm-modal>

                        <!-- Deletar -->
                        <app-confirm-modal
                          [btnClass]="'btn btn-danger shadow-sm btn-action'"
                          [modalTitle]="'Excluir Hotel'"
                          [message]="'Ação irreversível! Deseja realmente excluir o hotel ' + provider.name + '?'"
                          [okButtonLabel]="'Excluir'"
                          [tooltip]="'Excluir Hotel'"
                          (confirm)="deleteProvider(provider.id)">
                          <span modal-button><i class="fas fa-trash"></i></span>
                        </app-confirm-modal>
                      </div>
                    </td>
                  </tr>
                  <tr *ngFor="let i of [1, 2, 3, 4, 5].slice(0, isLoader ? 5 : 0)">
                    <td colspan="6" class="text-center py-3">
                      <div class="placeholder-glow">
                        <span class="placeholder col-12 rounded"></span>
                      </div>
                    </td>
                  </tr>
                  <tr *ngIf="providers.length === 0 && !isLoader">
                    <td colspan="6" class="text-center py-5 text-muted">
                      <i class="fas fa-folder-open fa-3x mb-3 d-block opacity-25"></i>
                      Nenhum hotel encontrado.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </app-datatable>
        </div>
      </div>
    </div>
  </div>
</app-authenticated-layout>

// resources/js/Pages/Auth/Auxiliaries/Hotel.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import Modal from '@/Components/Modal.vue';
import Loader from '@/Components/Loader.vue';
import { Head, useForm } from '@inertiajs/inertia-vue3';
import { onMounted, ref } from 'vue';


const props = defineProps({
    hotels: Array,
    cities: Array,
    aptos: Array,
    categories: Array,
});

const inEdition = ref(0);

const form = useForm({
    id: 0,
    name: '',
    city: '',
    contact: '',
    phone: '',
    email: '',
    aptos: [],
    categories: [],
    national: false,
    service_percent: null,
    iva_percent: null,
    iss_percent: null,
});

const formDelete = useForm({
    id: 0
});

onMounted(() => {

    $('#city').select2({
        theme: "bootstrap4",
        language: "pt-Br"
    }).on('select2:select', (e) => {
        form.city = e.params.data.id;
    });

    $('.phone').mask('(00) 00000-0000');

    $('table').DataTable({
        language: {
            url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/pt-BR.json',
        },
    });
});

const isLoader = ref(false);


const edit = (hotel) => {
    if (hotel != null) {
        form.reset();

        inEdition.value = hotel.id;
        form.id = hotel.id;
        form.name = hotel.name;
        form.contact = hotel.contact;
        form.phone = hotel.phone;
        form.email = hotel.email;
        form.national = hotel.national == true || hotel.national == 1;
        form.city = hotel.city;
        form.iss_percent = hotel.iss_percent;
        form.service_percent = hotel.service_percent;
        form.iva_percent = hotel.iva_percent;

        hotel.aptos.map(function (value, key) {
            form.aptos.push(value.id);
        });
        hotel.categories.map(function (value, key) {
            form.categories.push(value.id);
        });
        $('#city').val(hotel.city).trigger('change');

        $('.phone').val(form.phone).trigger('keyup');
    }
};

const newItem = (() => {
    form.reset();
    $('#city').val('').trigger('change');
    inEdition.value = 0;
});

const submit = () => {
    isLoader.value = true;
    form.post(route('hotel-save'), {
        onSuccess: () => {
            newItem();
            isLoader.value = false;
        },
    });
};

const deleteHotel = (id) => {
    isLoader.value = true;
    formDelete.id = id;
    formDelete.delete(route('hotel-delete'), {
        onFinish: () => {
            //isLoader.value = false;
            formDelete.reset();
        },
    });
};
</script>

<template>
    <AuthenticatedLayout>
        <Loader v-bind:show="isLoader"></Loader>

        <Head title="Fornecedor" />
        <template #header>
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Fornecedor</h1>
            </div>
        </template>

        <div class="row">
            <div class="col-lg-12">

                <div class="card mb-4 py-3 border-left-primary">
                    <div class="card-body">
                        <form @submit.prevent="submit()">

                            <div class="row">
                                <div class="col">

                                    <div class="form-group">
                                        <InputLabel for="name" value="Nome:" />
                                        <TextInput type="text" class="form-control" v-model="form.name" required autofocus
                                            autocomplete="name" />
                                        <InputError class="mt-2 text-danger" :message="form.errors.name" />
                                    </div>

                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <InputLabel for="city" value="Cidade:" />

                                        <select class="form-control" id="city" :required="required">
                                            <option>.::Selecione::.</option>
                                            <option v-for="(option, index) in cities" :selected="option.name == form.city"
                                                :value="option.name">
                                                {{ option.name }} - {{ option.uf }}
                                            </option>
                                        </select>

                                        <InputError class="mt-2 text-danger" :message="form.errors.city" />
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <InputLabel for="contact" value="Contato:" />
                                        <TextInput type="text" class="form-control" v-model="form.contact" required
                                            autofocus autocomplete="contact" />
                                        <InputError class="mt-2 text-danger" :message="form.errors.contact" />
                                    </div>

                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <InputLabel for="phone" value="Telefone:" />
                                        <TextInput id="phone" type="text" class="form-control phone" v-model="form.phone"
                                            required autofocus autocomplete="phone" />
                                        <InputError class="mt-2 text-danger" :message="form.errors.phone" />
                                    </div>

                                </div>
                            </div>

                            <div class="row">

                                <div class="col-3">
                                    <div class="form-group">
                                        <InputLabel for="email" value="E-mail:" />
                                        <TextInput type="email" class="form-control" v-model="form.email" required autofocus
                                            autocomplete="email" />
                                        <InputError class="mt-2 text-danger" :message="form.errors.email" />
                                    </div>
                                </div>

                                <div class="col-2">
                                    <div class="form-group">
                                        <InputLabel for="iss_percent" value="ISS:" />
                                        <TextInput type="number" class="form-control percent" v-model="form.iss_percent"
                                            required autofocus min="0" step=".1" autocomplete="iss_percent" />
                                    </div>
                                </div>

                                <div class="col-2">
                                    <div class="form-group">
                                        <InputLabel for="service_percent" value="Serviço:" />
                                        <TextInput type="number" class="form-control percent" v-model="form.service_percent"
                                            required autofocus min="0" step=".1" autocomplete="service_percent" />
                                    </div>
                                </div>

                                <div class="col-2">
                                    <div class="form-group">
                                        <InputLabel for="iva_percent" value="IVA:" />
                                        <TextInput type="number" class="form-control percent" v-model="form.iva_percent"
                                            required autofocus min="0" step=".1" autocomplete="iva_percent" />
                                    </div>
                                </div>

                                <div class="col">
                                    <div class="form-group">
                                        <InputLabel for="national" value=" " />

                                        <div class="card">
                                            <div class="card-body">
                                                <div class="form-check">
                                                    <input class="form-check-input" v-model="form.national" type="checkbox"
                                                        id="autoSizingCheck">
                                                    <label class="form-check-label" for="autoSizingCheck">
                                                        Fornecedor Nacional
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="flex items-center justify-end mt-4 rigth">
                                <PrimaryButton css-class="btn btn-primary float-right m-1"
                                    :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                    <span v-if="form.processing" class="spinner-border spinner-border-sm" role="status"
                                        aria-hidden="true"></span>
                                    Salvar
                                </PrimaryButton>
                                <PrimaryButton v-if="inEdition > 0" css-class="btn btn-info float-right m-1"
                                    v-on:click="newItem()" :class="{ 'opacity-25': form.processing }"
                                    :disabled="form.processing">
                                    Novo
                                </PrimaryButton>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="card mb-4 py-3 border-left-secondary">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped hotels-table" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Cidade</th>
                                        <th scope="col">Contato</th>
                                        <th scope="col">Telefone</th>
                                        <th scope="col">E-mail</th>
                                        <th scope="col">IVA</th>
                                        <th scope="col">ISS</th>
                                        <th scope="col">Serviço</th>
                                        <th scope="col">Tipo</th>
                                        <th scope="col">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr v-for="(hotel, index) in hotels" :class="{ 'table-info': inEdition == hotel.id }">
                                        <th scope="row">{{ hotel.id }}</th>
                                        <td>{{ hotel.name }}</td>
                                        <td>{{ hotel.city }}</td>
                                        <td>{{ hotel.contact }}</td>
                                        <td class="phone">{{ hotel.phone }}</td>
                                        <td>{{ hotel.email }}</td>
                                        <td>{{ hotel.iva_percent }}</td>
                                        <td>{{ hotel.iss_percent }}</td>
                                        <td>{{ hotel.service_percent }}</td>
                                        <td>{{ hotel.national ? "Nacional" : "Internacional" }}</td>
                                        <td>
                                            <button class="btn btn-info btn-icon-split mr-2" v-on:click="edit(hotel)">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-edit"></i>
                                                </span>
                                                <span class="text">Editar</span>
                                            </button>

                                            <Modal :key="index" :modal-title="'Confirmar Exclusão de ' + hotel.name"
                                                :ok-botton-callback="deleteHotel" :ok-botton-callback-param="hotel.id"
                                                btn-class="btn btn-danger btn-icon-split">
                                                <template v-slot:button>
                                                    <span class="icon text-white-50">
                                                        <i class="fas fa-trash"></i>
                                                    </span>
                                                    <span class="text">Excluir</span>
                                                </template>
                                                <template v-slot:content>
                                                    Tem certeza que deseja apagar esse registro?
                                                </template>
                                            </Modal>

                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </AuthenticatedLayout>
</template>
