// frontend/src/app/pages/transport/provider-transport/provider-transport.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';

import { ProviderTransportService, ProviderTransport, ProviderTransportCreateUpdateRequest } from '../../../services/provider-transport.service';
import { CityService } from '../../../services/city.service';
import { ToastService } from '../../../services/toast.service';
import { AuthenticatedLayoutComponent } from '../../../shared/layouts/authenticated-layout/authenticated-layout.component';
import { ConfirmModalComponent } from '../../../shared/components/confirm-modal/confirm-modal.component';
import { DatatableComponent } from '../../../shared/components/datatable/datatable.component';
import { AutocompleteComponent } from '../../../shared/components/autocomplete/autocomplete.component';
import { NgxMaskDirective } from 'ngx-mask';

@Component({
  selector: 'app-provider-transport',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    AuthenticatedLayoutComponent,
    ConfirmModalComponent,
    DatatableComponent,
    AutocompleteComponent,
    NgxMaskDirective
  ],
  templateUrl: './provider-transport.component.html',
  styleUrls: ['./provider-transport.component.scss'],
})
export class ProviderTransportComponent implements OnInit {
  private readonly providerTransportService: ProviderTransportService = inject(ProviderTransportService);
  private readonly cityService: CityService = inject(CityService);
  private readonly toastService: ToastService = inject(ToastService);

  providers: ProviderTransport[] = [];
  inEdition: number = 0;
  isLoader: boolean = false;
  processing: boolean = false;
  errors: any = {};
  showModal: boolean = false;

  // Pagination and Filtering state
  pagination: any = {
    current_page: 1,
    per_page: 10,
    total: 0,
    last_page: 1,
    from: 0,
    to: 0,
  };
  searchQuery: string = '';
  sortColumn: string = 'id';
  sortDirection: string = 'desc';

  selectedCityName: string = '';

  // Autocomplete Functions
  searchCities = (term: string) => this.cityService.searchCities(term);
  displayCity = (city: any) => (city ? `${city.name} - ${city.states ? city.states : city.country}` : '');

  form = {
    id: 0,
    name: '',
    city_id: undefined as number | undefined,
    contact: '',
    phone: '',
    email: '',
    national: true,
    iss_percent: null as number | null,
    service_percent: null as number | null,
    iva_percent: null as number | null,
    payment_method: '',
  };

  ngOnInit(): void {
    this.loadProviders();
  }

  loadProviders(): void {
    this.isLoader = true;
    const params = {
      page: this.pagination.current_page,
      per_page: this.pagination.per_page,
      search: this.searchQuery,
      sort_column: this.sortColumn,
      sort_direction: this.sortDirection,
    };

    this.providerTransportService.getProviders(params).subscribe({
      next: (response: any) => {
        this.providers = response.data || [];
        this.pagination = {
          current_page: response.current_page,
          per_page: response.per_page,
          total: response.total,
          last_page: response.last_page,
          from: response.from,
          to: response.to,
        };
        this.isLoader = false;
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao carregar fornecedores de transporte');
        console.error('Erro ao carregar fornecedores de transporte:', error);
      },
    });
  }

  onSearch(query: string): void {
    this.searchQuery = query;
    this.pagination.current_page = 1;
    this.loadProviders();
  }

  onPageChange(page: number): void {
    this.pagination.current_page = page;
    this.loadProviders();
  }

  onPerPageChange(perPage: number): void {
    this.pagination.per_page = perPage;
    this.pagination.current_page = 1;
    this.loadProviders();
  }

  sortBy(column: string): void {
    if (this.sortColumn === column) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortColumn = column;
      this.sortDirection = 'asc';
    }
    this.loadProviders();
  }

  openModal(): void {
    this.resetForm();
    this.showModal = true;
  }

  closeModal(): void {
    this.showModal = false;
    this.resetForm();
  }

  edit(provider: ProviderTransport): void {
    this.inEdition = provider.id;
    this.form = {
      id: provider.id,
      name: provider.name,
      city_id: provider.city_id,
      contact: provider.contact,
      phone: provider.phone,
      email: provider.email,
      national: String(provider.national) === '1' || String(provider.national) === 'true',
      iss_percent: provider.iss_percent ?? null,
      service_percent: provider.service_percent ?? null,
      iva_percent: provider.iva_percent ?? null,
      payment_method: provider.payment_method ?? '',
    };

    this.selectedCityName = provider.city
      ? `${provider.city.name} - ${provider.city.states ? provider.city.states : provider.city.country}`
      : '';
    this.errors = {};
    this.showModal = true;
  }

  cancelEdit(): void {
    this.closeModal();
  }

  resetForm(): void {
    this.form = {
      id: 0,
      name: '',
      city_id: undefined,
      contact: '',
      phone: '',
      email: '',
      national: true,
      iss_percent: null,
      service_percent: null,
      iva_percent: null,
      payment_method: '',
    };
    this.selectedCityName = '';
    this.errors = {};
    this.inEdition = 0;
  }

  private validateForm(): boolean {
    this.errors = {};
    let isValid = true;

    if (!this.form.name || this.form.name.trim() === '') {
      this.errors.name = ['O nome é obrigatório'];
      isValid = false;
    }

    if (!this.form.contact || this.form.contact.trim() === '') {
      this.errors.contact = ['O contato é obrigatório'];
      isValid = false;
    }

    if (!this.form.phone || this.form.phone.trim() === '') {
      this.errors.phone = ['O telefone é obrigatório'];
      isValid = false;
    }

    if (!this.form.email || this.form.email.trim() === '') {
      this.errors.email = ['O e-mail é obrigatório'];
      isValid = false;
    } else {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(this.form.email)) {
        this.errors.email = ['O e-mail informado é inválido'];
        isValid = false;
      }
    }

    if (!this.form.city_id) {
      this.errors.city_id = ['A cidade é obrigatória'];
      isValid = false;
    }

    return isValid;
  }

  submit(): void {
    if (!this.validateForm()) {
      return;
    }

    this.processing = true;

    const data: ProviderTransportCreateUpdateRequest = {
      id: this.form.id,
      name: this.form.name,
      city_id: this.form.city_id,
      contact: this.form.contact,
      phone: this.form.phone,
      email: this.form.email,
      national: this.form.national,
      iss_percent: this.form.iss_percent,
      service_percent: this.form.service_percent,
      iva_percent: this.form.iva_percent,
      payment_method: this.form.payment_method || null,
    };

    this.providerTransportService.saveProvider(data).subscribe({
      next: (response: any) => {
        this.processing = false;
        this.toastService.success(response.message || 'Fornecedor de transporte salvo com sucesso');
        this.closeModal();
        this.loadProviders();
      },
      error: (error: HttpErrorResponse) => {
        this.processing = false;
        if (error.status === 422) {
          this.errors = error.error.errors || {};
        } else {
          this.toastService.error('Erro ao salvar fornecedor de transporte');
        }
        console.error('Erro ao salvar fornecedor de transporte:', error);
      },
    });
  }

  deleteProvider(id: number): void {
    this.isLoader = true;
    this.providerTransportService.deleteProvider(id).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Fornecedor de transporte apagado com sucesso');
        this.loadProviders();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao apagar fornecedor de transporte');
        console.error('Erro ao deletar fornecedor de transporte:', error);
      },
    });
  }

  activateProvider(id: number): void {
    this.isLoader = true;
    this.providerTransportService.activateProvider(id).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Fornecedor de transporte ativado com sucesso');
        this.loadProviders();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao ativar fornecedor de transporte');
        console.error('Erro ao ativar fornecedor de transporte:', error);
      },
    });
  }

  deactivateProvider(id: number): void {
    this.isLoader = true;
    this.providerTransportService.deactivateProvider(id).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Fornecedor de transporte inativado com sucesso');
        this.loadProviders();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao inativar fornecedor de transporte');
        console.error('Erro ao inativar fornecedor de transporte:', error);
      },
    });
  }

  isProviderInEdition(id: number): boolean {
    return this.inEdition === id;
  }
}

<app-authenticated-layout>
  <ng-container header>
    <div class="d-sm-flex align-items-center justify-content-between mb-4 animate-in">
      <h1 class="h3 mb-0 text-gray-800">Gerenciamento de Fornecedores de Transporte</h1>
    </div>
  </ng-container>

  <div class="row position-relative">
    <!-- Modal de Cadastro/Edição -->
    <div class="modal fade" 
         [class.show]="showModal" 
         [style.display]="showModal ? 'block' : 'none'" 
         [style.background]="showModal ? 'rgba(0,0,0,0.5)' : ''" 
         tabindex="-1" 
         role="dialog" 
         aria-labelledby="providerTransModalLabel" 
         aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content border-0 shadow-lg rounded-3xl animate-in">
          <div class="modal-header bg-light">
            <h5 class="modal-title font-weight-bold text-primary" id="providerTransModalLabel">
              <i class="fas fa-edit me-2"></i>{{ inEdition > 0 ? 'Editar Fornecedor de Transporte' : 'Cadastrar Novo Fornecedor de Transporte' }}
            </h5>
            <button type="button" class="btn-close" (click)="closeModal()" aria-label="Fechar" [disabled]="processing"></button>
          </div>
          <form (ngSubmit)="submit()">
            <div class="modal-body p-4">
              <div class="row align-items-start">

                <!-- Nome -->
                <div class="col-lg-6 mb-3">
                  <div class="form-group mb-0">
                    <label for="name" class="form-label">Nome: <span class="text-danger">*</span></label>
                    <input 
                      type="text" 
                      id="name" 
                      class="form-control" 
                      [class.is-invalid]="errors['name']"
                      [(ngModel)]="form.name" 
                      name="name" 
                      placeholder="Ex: Fornecedor Transporte ABC"
                      required 
                      autofocus>
                    
                    <div *ngIf="errors['name']" class="text-danger mt-1">
                      <small *ngFor="let err of errors['name']" class="d-block">{{ err }}</small>
                    </div>
                  </div>
                </div>

                <!-- Município (Autocomplete) -->
                <div class="col-lg-6 mb-3">
                  <app-autocomplete
                    id="city"
                    label="Cidade"
                    placeholder="Digite para buscar a cidade..."
                    [required]="true"
                    [searchFn]="searchCities"
                    [displayFn]="displayCity"
                    valueField="id"
                    [initialText]="selectedCityName"
                    [(ngModel)]="form.city_id"
                    name="city"
                    [errors]="errors['city_id']">
                  </app-autocomplete>
                </div>

                <!-- Contato -->
                <div class="col-lg-6 mb-3">
                  <div class="form-group mb-0">
                    <label for="contact" class="form-label">Contato: <span class="text-danger">*</span></label>
                    <input 
                      type="text" 
                      id="contact" 
                      class="form-control" 
                      [class.is-invalid]="errors['contact']"
                      [(ngModel)]="form.contact" 
                      name="contact" 
                      placeholder="Ex: João Silva"
                      required>
                    
                    <div *ngIf="errors['contact']" class="text-danger mt-1">
                      <small *ngFor="let err of errors['contact']" class="d-block">{{ err }}</small>
                    </div>
                  </div>
                </div>

                <!-- Telefone -->
                <div class="col-lg-6 mb-3">
                  <div class="form-group mb-0">
                    <label for="phone" class="form-label">Telefone: <span class="text-danger">*</span></label>
                    <input 
                      type="text" 
                      id="phone" 
                      class="form-control" 
                      [class.is-invalid]="errors['phone']"
                      [(ngModel)]="form.phone" 
                      name="phone" 
                      placeholder="Ex: (11) 99999-9999"
                      mask="(00) 0000-00009"
                      [dropSpecialCharacters]="false"
                      required>
                    
                    <div *ngIf="errors['phone']" class="text-danger mt-1">
                      <small *ngFor="let err of errors['phone']" class="d-block">{{ err }}</small>
                    </div>
                  </div>
                </div>

                <!-- E-mail -->
                <div class="col-lg-8 mb-3">
                  <div class="form-group mb-0">
                    <label for="email" class="form-label">E-mail: <span class="text-danger">*</span></label>
                    <input 
                      type="email" 
                      id="email" 
                      class="form-control" 
                      [class.is-invalid]="errors['email']"
                      [(ngModel)]="form.email" 
                      name="email" 
                      placeholder="exemplo@email.com"
                      required>
                    
                    <div *ngIf="errors['email']" class="text-danger mt-1">
                      <small *ngFor="let err of errors['email']" class="d-block">{{ err }}</small>
                    </div>
                  </div>
                </div>

                <!-- Nacional Toggle -->
                <div class="col-lg-4 mb-3">
                  <label class="form-label d-block">Nacional?</label>
                  <div class="form-switch mt-2">
                    <input class="form-check-input cursor-pointer" type="checkbox" id="national" [(ngModel)]="form.national" name="national" />
                    <label class="form-check-label cursor-pointer text-muted ms-2" for="national">{{ form.national ? 'Sim' : 'Não' }}</label>
                  </div>
                </div>

                <!-- Separador -->
                <div class="col-12 mb-3">
                  <hr class="my-1">
                  <small class="text-muted">Informações Fiscais (opcional)</small>
                </div>

                <!-- ISS (%) -->
                <div class="col-lg-4 mb-3">
                  <div class="form-group mb-0">
                    <label for="iss_percent" class="form-label">ISS (%):</label>
                    <input 
                      type="number" 
                      id="iss_percent" 
                      class="form-control" 
                      [class.is-invalid]="errors['iss_percent']"
                      [(ngModel)]="form.iss_percent" 
                      name="iss_percent" 
                      placeholder="Ex: 5.00"
                      min="0" 
                      max="100"
                      step="0.01">
                    
                    <div *ngIf="errors['iss_percent']" class="text-danger mt-1">
                      <small *ngFor="let err of errors['iss_percent']" class="d-block">{{ err }}</small>
                    </div>
                  </div>
                </div>

                <!-- Serviço (%) -->
                <div class="col-lg-4 mb-3">
                  <div class="form-group mb-0">
                    <label for="service_percent" class="form-label">Serviço (%):</label>
                    <input 
                      type="number" 
                      id="service_percent" 
                      class="form-control" 
                      [class.is-invalid]="errors['service_percent']"
                      [(ngModel)]="form.service_percent" 
                      name="service_percent" 
                      placeholder="Ex: 10.00"
                      min="0" 
                      max="100"
                      step="0.01">
                    
                    <div *ngIf="errors['service_percent']" class="text-danger mt-1">
                      <small *ngFor="let err of errors['service_percent']" class="d-block">{{ err }}</small>
                    </div>
                  </div>
                </div>

                <!-- IVA (%) -->
                <div class="col-lg-4 mb-3">
                  <div class="form-group mb-0">
                    <label for="iva_percent" class="form-label">IVA (%):</label>
                    <input 
                      type="number" 
                      id="iva_percent" 
                      class="form-control" 
                      [class.is-invalid]="errors['iva_percent']"
                      [(ngModel)]="form.iva_percent" 
                      name="iva_percent" 
                      placeholder="Ex: 21.00"
                      min="0" 
                      max="100"
                      step="0.01">
                    
                    <div *ngIf="errors['iva_percent']" class="text-danger mt-1">
                      <small *ngFor="let err of errors['iva_percent']" class="d-block">{{ err }}</small>
                    </div>
                  </div>
                </div>

                <!-- Forma de Pagamento -->
                <div class="col-lg-12 mb-3">
                  <div class="form-group mb-0">
                    <label for="payment_method" class="form-label">Forma de Pagamento:</label>
                    <input 
                      type="text" 
                      id="payment_method" 
                      class="form-control" 
                      [class.is-invalid]="errors['payment_method']"
                      [(ngModel)]="form.payment_method" 
                      name="payment_method" 
                      placeholder="Ex: Transferência Bancária, Boleto...">
                    
                    <div *ngIf="errors['payment_method']" class="text-danger mt-1">
                      <small *ngFor="let err of errors['payment_method']" class="d-block">{{ err }}</small>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer bg-light border-0">
              <button type="button" class="btn btn-outline-secondary" (click)="closeModal()" [disabled]="processing">
                <i class="fas fa-times me-1"></i> Cancelar
              </button>
              <button type="submit" class="btn btn-primary shadow-sm" [disabled]="processing">
                <span *ngIf="processing" class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
                <i *ngIf="!processing" class="fas fa-save me-1"></i> Salvar
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <!-- Table Section -->
    <div class="col-lg-12 animate-in" style="animation-delay: 0.2s;">
      <div class="card mb-4 border-left-secondary">
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between mb-4">
            <h5 class="card-title mb-0 text-secondary font-weight-bold">
              <i class="fas fa-list me-2"></i>Lista de Fornecedores de Transporte
            </h5>
            <button class="btn btn-primary btn-sm shadow-sm" (click)="openModal()" [disabled]="processing">
              <i class="fas fa-plus me-1"></i> Novo Fornecedor
            </button>
          </div>

          <app-datatable 
            [pagination]="pagination" 
            [loading]="isLoader"
            (search)="onSearch($event)"
            (pageChange)="onPageChange($event)"
            (perPageChange)="onPerPageChange($event)">
            
            <div class="table-responsive">
              <table class="table table-hover" width="100%" cellspacing="0">
                <thead class="table-light">
                  <tr>
                    <th scope="col" (click)="sortBy('id')" style="cursor: pointer; width: 80px;">
                      <div class="d-flex align-items-center">
                        ID <i class="fas fa-sort ms-2 text-muted" [ngClass]="{'fa-sort-up text-primary': sortColumn === 'id' && sortDirection === 'asc', 'fa-sort-down text-primary': sortColumn === 'id' && sortDirection === 'desc'}"></i>
                      </div>
                    </th>
                    <th scope="col" (click)="sortBy('name')" style="cursor: pointer;">
                      <div class="d-flex align-items-center">
                        Nome <i class="fas fa-sort ms-2 text-muted" [ngClass]="{'fa-sort-up text-primary': sortColumn === 'name' && sortDirection === 'asc', 'fa-sort-down text-primary': sortColumn === 'name' && sortDirection === 'desc'}"></i>
                      </div>
                    </th>
                    <th scope="col">Município</th>
                    <th scope="col" (click)="sortBy('contact')" style="cursor: pointer;">
                      <div class="d-flex align-items-center">
                        Contato <i class="fas fa-sort ms-2 text-muted" [ngClass]="{'fa-sort-up text-primary': sortColumn === 'contact' && sortDirection === 'asc', 'fa-sort-down text-primary': sortColumn === 'contact' && sortDirection === 'desc'}"></i>
                      </div>
                    </th>
                    <th scope="col">Telefone</th>
                    <th scope="col" (click)="sortBy('email')" style="cursor: pointer;">
                      <div class="d-flex align-items-center">
                        E-mail <i class="fas fa-sort ms-2 text-muted" [ngClass]="{'fa-sort-up text-primary': sortColumn === 'email' && sortDirection === 'asc', 'fa-sort-down text-primary': sortColumn === 'email' && sortDirection === 'desc'}"></i>
                      </div>
                    </th>
                    <th scope="col">Tipo</th>
                    <th scope="col" class="text-end">Ações</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let provider of providers" [class.table-info]="isProviderInEdition(provider.id)">
                    <th scope="row" class="font-weight-bold">{{ provider.id }}</th>
                    <td>
                      <span [class.text-muted]="!provider.active">{{ provider.name }}</span>
                      <span *ngIf="!provider.active" class="badge bg-light text-muted ms-2">Inativo</span>
                    </td>
                    <td>
                      <span [class.text-muted]="!provider.active">{{ provider.city ? provider.city.name + ' - ' + (provider.city.states ? provider.city.states : provider.city.country) : '-' }}</span>
                    </td>
                    <td><span [class.text-muted]="!provider.active">{{ provider.contact }}</span></td>
                    <td><span [class.text-muted]="!provider.active">{{ provider.phone }}</span></td>
                    <td><span [class.text-muted]="!provider.active">{{ provider.email }}</span></td>
                    <td>
                      <span class="badge" [ngClass]="provider.national ? 'bg-primary' : 'bg-info text-white'">
                        {{ provider.national ? 'Nacional' : 'Internacional' }}
                      </span>
                    </td>
                    <td class="text-end">
                      <div class="d-flex justify-content-end gap-2 flex-wrap">
                        <!-- Editar -->
                        <button class="btn btn-sm btn-info text-white shadow-sm" (click)="edit(provider)" title="Editar">
                          <i class="fas fa-edit me-1"></i> Editar
                        </button>

                        <!-- Ativar -->
                        <button *ngIf="!provider.active" class="btn btn-sm btn-success shadow-sm" (click)="activateProvider(provider.id)" title="Ativar">
                          <i class="fas fa-check me-1"></i> Ativar
                        </button>

                        <!-- Inativar -->
                        <app-confirm-modal 
                          *ngIf="provider.active"
                          [btnClass]="'btn btn-sm btn-warning shadow-sm'" 
                          [modalTitle]="'Inativar Fornecedor'" 
                          [message]="'Tem certeza que deseja inativar o fornecedor ' + provider.name + '?'"
                          [okButtonLabel]="'Confirmar'"
                          (confirm)="deactivateProvider(provider.id)">
                          <span modal-button><i class="fas fa-ban me-1"></i> Inativar</span>
                        </app-confirm-modal>

                        <!-- Deletar -->
                        <app-confirm-modal 
                          [btnClass]="'btn btn-sm btn-danger shadow-sm'" 
                          [modalTitle]="'Excluir Fornecedor'" 
                          [message]="'Ação irreversível! Deseja realmente excluir o fornecedor ' + provider.name + '?'"
                          [okButtonLabel]="'Excluir'"
                          (confirm)="deleteProvider(provider.id)">
                          <span modal-button><i class="fas fa-trash me-1"></i> Excluir</span>
                        </app-confirm-modal>
                      </div>
                    </td>
                  </tr>

                  <!-- Placeholders de carregamento -->
                  <tr *ngFor="let i of [1,2,3,4,5].slice(0, isLoader ? 5 : 0)">
                    <td colspan="8" class="text-center py-3">
                      <div class="placeholder-glow">
                        <span class="placeholder col-12 rounded"></span>
                      </div>
                    </td>
                  </tr>

                  <!-- Sem resultados -->
                  <tr *ngIf="providers.length === 0 && !isLoader">
                    <td colspan="8" class="text-center py-5 text-muted">
                      <i class="fas fa-folder-open fa-3x mb-3 d-block opacity-25"></i>
                      Nenhum fornecedor de transporte encontrado.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </app-datatable>
        </div>
      </div>
    </div>
  </div>
</app-authenticated-layout>

// resources/js/Pages/Auth/Auxiliaries/ProviderTransport.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import Modal from '@/Components/Modal.vue';
import Loader from '@/Components/Loader.vue';
import { Head, useForm } from '@inertiajs/inertia-vue3';
import { onMounted, ref } from 'vue';


const props = defineProps({
    hotels: Array,
    cities: Array,
    aptos: Array,
    categories: Array,
});

const inEdition = ref(0);

const form = useForm({
    id: 0,
    name: '',
    city: '',
    contact: '',
    phone: '',
    email: '',
    aptos: [],
    categories: [],
    national: false,
    service_percent: null,
    iva_percent: null,
    iss_percent: null,
});


const formDelete = useForm({
    id: 0
});

onMounted(() => {

    $('#city').select2({
        theme: "bootstrap4",
        language: "pt-Br"
    }).on('select2:select', (e) => {
        form.city = e.params.data.id;
    });


    $('table').DataTable({
        language: {
            url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/pt-BR.json',
        },
    });
});

const isLoader = ref(false);


const edit = (hotel) => {

    if (hotel != null) {
        form.reset();

        inEdition.value = hotel.id;
        form.id = hotel.id;
        form.name = hotel.name;
        form.contact = hotel.contact;
        form.phone = hotel.phone;
        form.email = hotel.email;
        form.national = hotel.national == true || hotel.national == 1;
        form.city = hotel.city_id;
        form.iss_percent = hotel.iss_percent;
        form.service_percent = hotel.service_percent;
        form.iva_percent = hotel.iva_percent;

        $('#city').val(hotel.city_id).trigger('change');
        $('.phone').val(form.phone).trigger('keyup');
    }
};

const newItem = (() => {
    form.reset();
    $('#city').val('').trigger('change');
    inEdition.value = 0;
});

const submit = () => {
    isLoader.value = true;
    form.post(route('provider-transport-save'), {
        onSuccess: () => {
            newItem();
            isLoader.value = false;
        },
    });
};

const deleteHotel = (id) => {
    isLoader.value = true;
    formDelete.id = id;
    formDelete.delete(route('provider-transport-delete'), {
        onFinish: () => {
            isLoader.value = false;
            formDelete.reset();
        },
    });
};


const activate = (id) => {
    isLoader.value = true;
    form.put(route('provider_transports-activate', id), {
        onFinish: () => {
            isLoader.value = false;
        },
    });
};

const deactivate = (id) => {
    isLoader.value = true;
    form.put(route('provider_transports-deactivate', id), {
        onFinish: () => {
            isLoader.value = false;
        },
    });
};
</script>

<template>
    <AuthenticatedLayout>
        <Loader v-bind:show="isLoader"></Loader>

        <Head title="Fornecedor" />
        <template #header>
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Fornecedor</h1>
            </div>
        </template>

        <div class="row">
            <div class="col-lg-12">

                <div class="card mb-4 py-3 border-left-primary">
                    <div class="card-body">
                        <form @submit.prevent="submit()">

                            <div class="row">
                                <div class="col">

                                    <div class="form-group">
                                        <InputLabel for="name" value="Nome:" />
                                        <TextInput type="text" class="form-control" v-model="form.name" required autofocus
                                            autocomplete="name" />
                                        <InputError class="mt-2 text-danger" :message="form.errors.name" />
                                    </div>

                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <InputLabel for="city" value="Cidade:" />

                                        <select class="form-control" id="city" :required="required">
                                            <option value="">.::Selecione::.</option>
                                            <option v-for="(option, index) in cities" :value="option.id">
                                                {{ option.name }} - {{ option.states ? option.states :
                                                    option.country }}
                                            </option>
                                        </select>

                                        <InputError class="mt-2 text-danger" :message="form.errors.city" />
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <InputLabel for="contact" value="Contato:" />
                                        <TextInput type="text" class="form-control" v-model="form.contact" autofocus
                                            autocomplete="contact" required />
                                        <InputError class="mt-2 text-danger" :message="form.errors.contact" />
                                    </div>

                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <InputLabel for="phone" value="Telefone:" />
                                        <TextInput id="phone" type="text" class="form-control phone" v-model="form.phone"
                                            autofocus autocomplete="phone" />
                                        <InputError class="mt-2 text-danger" :message="form.errors.phone" />
                                    </div>

                                </div>
                            </div>

                            <div class="row">

                                <div class="col-3">
                                    <div class="form-group">
                                        <InputLabel for="email" value="E-mail:" />
                                        <TextInput type="email" class="form-control" v-model="form.email" autofocus
                                            autocomplete="email" />
                                        <InputError class="mt-2 text-danger" :message="form.errors.email" />
                                    </div>
                                </div>

                                <div class="col-2">
                                    <div class="form-group">
                                        <InputLabel for="iss_percent" value="ISS:" />
                                        <TextInput type="number" class="form-control percent" v-model="form.iss_percent"
                                            required autofocus min="0" step="0.01" autocomplete="iss_percent" />
                                    </div>
                                </div>

                                <div class="col-2">
                                    <div class="form-group">
                                        <InputLabel for="service_percent" value="Serviço:" />
                                        <TextInput type="number" class="form-control percent" v-model="form.service_percent"
                                            required autofocus min="0" step="0.01" autocomplete="service_percent" />
                                    </div>
                                </div>

                                <div class="col-2">
                                    <div class="form-group">
                                        <InputLabel for="iva_percent" value="IVA:" />
                                        <TextInput type="number" class="form-control percent" v-model="form.iva_percent"
                                            required autofocus min="0" step="0.01" autocomplete="iva_percent" />
                                    </div>
                                </div>

                                <div class="col">
                                    <div class="form-group">
                                        <InputLabel for="national" value=" " />

                                        <div class="card">
                                            <div class="card-body">
                                                <div class="form-check">
                                                    <input class="form-check-input" v-model="form.national" :value="true"
                                                        type="radio" id="autoSizingCheck1">
                                                    <label class="form-check-label" for="autoSizingCheck1">
                                                        Fornecedor Nacional
                                                    </label>
                                                </div>
                                                <div class="form-check">
                                                    <input class="form-check-input" v-model="form.national" :value="false"
                                                        type="radio" id="autoSizingCheck">
                                                    <label class="form-check-label" for="autoSizingCheck">
                                                        Fornecedor Internacional
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="flex items-center justify-end mt-4 rigth">
                                <PrimaryButton css-class="btn btn-primary float-right m-1"
                                    :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                    <span v-if="form.processing" class="spinner-border spinner-border-sm" role="status"
                                        aria-hidden="true"></span>
                                    Salvar
                                </PrimaryButton>
                                <PrimaryButton v-if="inEdition > 0" css-class="btn btn-info float-right m-1"
                                    v-on:click="newItem()" :class="{ 'opacity-25': form.processing }"
                                    :disabled="form.processing">
                                    Novo
                                </PrimaryButton>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="card mb-4 py-3 border-left-secondary">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-sm table-striped hotels-table" id="dataTable" width="100%"
                                cellspacing="0">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Cidade</th>
                                        <th scope="col">Contato</th>
                                        <th scope="col">Telefone</th>
                                        <th scope="col">E-mail</th>
                                        <th scope="col">Tipo</th>
                                        <th scope="col">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr v-for="(hotel, index) in hotels" :class="{ 'table-info': inEdition == hotel.id }">
                                        <th scope="row">{{ hotel.id }}</th>
                                        <td>{{ hotel.name }}</td>
                                        <td>{{ hotel.city?.name || ' - ' }} - {{ hotel.city?.states ?
                                            hotel.city.states :
                                            hotel.city?.country || ' - ' }}</td>
                                        <td>{{ hotel.contact }}</td>
                                        <td class="phone">{{ hotel.phone }}</td>
                                        <td>{{ hotel.email }}</td>
                                        <td>{{ hotel.national ? "Nacional" : "Internacional" }}</td>
                                        <td>
                                            <button class="btn btn-sm btn-info btn-icon-split mr-2"
                                                v-on:click="edit(hotel)">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-edit"></i>
                                                </span>
                                                <span class="text">Editar</span>
                                            </button>

                                            <Modal :key="index" :modal-title="'Confirmar Exclusão de ' + hotel.name"
                                                :ok-botton-callback="deleteHotel" :ok-botton-callback-param="hotel.id"
                                                btn-class="btn btn-sm btn-danger btn-icon-split mr-2">
                                                <template v-slot:button>
                                                    <span class="icon text-white-50">
                                                        <i class="fas fa-trash"></i>
                                                    </span>
                                                    <span class="text">Excluir</span>
                                                </template>
                                                <template v-slot:content>
                                                    Tem certeza que deseja apagar esse registro?
                                                </template>
                                            </Modal>


                                            <button v-if="!hotel.active" class="btn btn-sm btn-success btn-icon-split mr-2"
                                                        v-on:click="activate(hotel.id)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-check"></i>
                                                        </span>
                                                        <span class="text">Ativar</span>
                                                    </button>

                                                    <button v-if="hotel.active" class="btn btn-sm btn-warning btn-icon-split mr-2"
                                                        v-on:click="deactivate(hotel.id)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-ban"></i>
                                                        </span>
                                                        <span class="text">Inativar</span>
                                                    </button>

                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </AuthenticatedLayout>
</template>
