// frontend/src/app/pages/adds/service-add/service-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';

import { ServiceAddService, ServiceAdd, ServiceAddCreateUpdateRequest } from '../../../services/service-add.service';
import { ToastService } from '../../../services/toast.service';
import { AuthenticatedLayoutComponent } from '../../../shared/layouts/authenticated-layout/authenticated-layout.component';
import { ConfirmModalComponent } from '../../../shared/components/confirm-modal/confirm-modal.component';
import { DatatableComponent } from '../../../shared/components/datatable/datatable.component';

@Component({
  selector: 'app-service-add',
  standalone: true,
  imports: [CommonModule, FormsModule, AuthenticatedLayoutComponent, ConfirmModalComponent, DatatableComponent],
  templateUrl: './service-add.component.html',
  styleUrls: ['./service-add.component.scss'],
})
export class ServiceAddComponent implements OnInit {
  private readonly serviceAddService: ServiceAddService = inject(ServiceAddService);
  private readonly toastService: ToastService = inject(ToastService);

  serviceAdds: ServiceAdd[] = [];
  inEdition: number = 0;
  isLoader: boolean = false;
  processing: boolean = false;
  errors: any = {};

  // Pagination and Filtering state
  pagination: any = {
    current_page: 1,
    per_page: 10,
    total: 0,
    last_page: 1,
    from: 0,
    to: 0,
  };
  searchQuery: string = '';
  sortColumn: string = 'id';
  sortDirection: string = 'desc';

  form = {
    id: 0,
    name: '',
  };

  ngOnInit(): void {
    this.loadServiceAdds();
  }

  loadServiceAdds(): void {
    this.isLoader = true;
    const params = {
      page: this.pagination.current_page,
      per_page: this.pagination.per_page,
      search: this.searchQuery,
      sort_column: this.sortColumn,
      sort_direction: this.sortDirection,
    };

    this.serviceAddService.getServiceAdds(params).subscribe({
      next: (response: any) => {
        this.serviceAdds = response.data || [];
        this.pagination = {
          current_page: response.current_page,
          per_page: response.per_page,
          total: response.total,
          last_page: response.last_page,
          from: response.from,
          to: response.to,
        };
        this.isLoader = false;
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao carregar serviços adicionais');
        console.error('Erro ao carregar serviços adicionais:', error);
      },
    });
  }

  onSearch(query: string): void {
    this.searchQuery = query;
    this.pagination.current_page = 1;
    this.loadServiceAdds();
  }

  onPageChange(page: number): void {
    this.pagination.current_page = page;
    this.loadServiceAdds();
  }

  onPerPageChange(perPage: number): void {
    this.pagination.per_page = perPage;
    this.pagination.current_page = 1;
    this.loadServiceAdds();
  }

  sortBy(column: string): void {
    if (this.sortColumn === column) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortColumn = column;
      this.sortDirection = 'asc';
    }
    this.loadServiceAdds();
  }

  edit(serviceAdd: ServiceAdd): void {
    this.inEdition = serviceAdd.id;
    this.form.id = serviceAdd.id;
    this.form.name = serviceAdd.name;
    this.errors = {};
  }

  resetForm(): void {
    this.form = {
      id: 0,
      name: '',
    };
    this.errors = {};
    this.inEdition = 0;
  }

  private validateForm(): boolean {
    this.errors = {};

    if (!this.form.name || this.form.name.trim() === '') {
      this.errors.name = ['O nome é obrigatório'];
      return false;
    }

    return true;
  }

  submit(): void {
    if (!this.validateForm()) {
      return;
    }

    this.processing = true;

    const data: ServiceAddCreateUpdateRequest = {
      id: this.form.id,
      name: this.form.name,
    };

    this.serviceAddService.saveServiceAdd(data).subscribe({
      next: (response: any) => {
        this.processing = false;
        this.toastService.success(response.message || 'Serviço salvo com sucesso');
        this.resetForm();
        this.loadServiceAdds();
      },
      error: (error: HttpErrorResponse) => {
        this.processing = false;
        if (error.status === 422) {
          this.errors = error.error.errors || {};
        } else {
          this.toastService.error('Erro ao salvar serviço');
        }
        console.error('Erro ao salvar serviço:', error);
      },
    });
  }

  deleteServiceAdd(serviceAddId: number): void {
    this.isLoader = true;
    this.serviceAddService.deleteServiceAdd(serviceAddId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Serviço apagado com sucesso');
        this.loadServiceAdds();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao apagar serviço');
        console.error('Erro ao deletar serviço:', error);
      },
    });
  }

  activateServiceAdd(serviceAddId: number): void {
    this.isLoader = true;
    this.serviceAddService.activateServiceAdd(serviceAddId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Serviço ativado com sucesso');
        this.loadServiceAdds();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao ativar serviço');
        console.error('Erro ao ativar serviço:', error);
      },
    });
  }

  deactivateServiceAdd(serviceAddId: number): void {
    this.isLoader = true;
    this.serviceAddService.deactivateServiceAdd(serviceAddId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Serviço inativado com sucesso');
        this.loadServiceAdds();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao inativar serviço');
        console.error('Erro ao inativar serviço:', error);
      },
    });
  }

  isServiceAddInEdition(serviceAddId: number): boolean {
    return this.inEdition === serviceAddId;
  }
}

<app-authenticated-layout>
  <ng-container header>
    <div class="d-sm-flex align-items-center justify-content-between mb-4 animate-in">
      <h1 class="h3 mb-0 text-gray-800">Gerenciamento de Serviços Adicionais</h1>
    </div>
  </ng-container>

  <div class="row position-relative">
    <!-- Form Section -->
    <div class="col-lg-12 animate-in" style="animation-delay: 0.1s">
      <div class="card mb-4 border-left-primary">
        <div class="card-body">
          <h5 class="card-title mb-4 text-primary font-weight-bold">
            <i class="fas fa-plus-circle me-2"></i>
            {{ inEdition > 0 ? 'Editar Serviço Adicional' : 'Novo Serviço Adicional' }}
          </h5>
          <form (ngSubmit)="submit()">
            <div class="row align-items-end">
              <div class="col-lg-8">
                <div class="form-group mb-0">
                  <label for="name" class="form-label">
                    Nome do Serviço
                    <span class="text-danger">*</span>
                  </label>
                  <input type="text" id="name" class="form-control" [(ngModel)]="form.name" name="name" placeholder="Ex: Limpeza Extra" required autofocus />

                  <div *ngIf="errors['name']" class="text-danger mt-1">
                    <small *ngFor="let err of errors['name']" class="d-block">{{ err }}</small>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="d-flex align-items-center justify-content-end">
                  <button type="button" *ngIf="inEdition > 0" class="btn btn-outline-secondary me-2" (click)="resetForm()" [disabled]="processing">
                    <i class="fas fa-times me-1"></i>
                    Cancelar
                  </button>

                  <button type="submit" class="btn btn-primary shadow-sm" [disabled]="processing" [class.opacity-50]="processing">
                    <span *ngIf="processing" class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
                    <i *ngIf="!processing" class="fas fa-save me-1"></i>
                    Salvar
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

    <!-- Table Section -->
    <div class="col-lg-12 animate-in" style="animation-delay: 0.2s">
      <div class="card mb-4 border-left-secondary">
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between mb-4">
            <h5 class="card-title mb-0 text-secondary font-weight-bold">
              <i class="fas fa-list me-2"></i>
              Lista de Serviços Adicionais
            </h5>
          </div>

          <app-datatable
            [pagination]="pagination"
            [loading]="isLoader"
            (search)="onSearch($event)"
            (pageChange)="onPageChange($event)"
            (perPageChange)="onPerPageChange($event)">
            <div class="table-responsive">
              <table class="table table-hover" width="100%" cellspacing="0">
                <thead class="table-light">
                  <tr>
                    <th scope="col" (click)="sortBy('id')" style="cursor: pointer; width: 80px">
                      <div class="d-flex align-items-center">
                        ID
                        <i
                          class="fas fa-sort ms-2 text-muted"
                          [ngClass]="{
                            'fa-sort-up text-primary': sortColumn === 'id' && sortDirection === 'asc',
                            'fa-sort-down text-primary': sortColumn === 'id' && sortDirection === 'desc',
                          }"></i>
                      </div>
                    </th>
                    <th scope="col" (click)="sortBy('name')" style="cursor: pointer">
                      <div class="d-flex align-items-center">
                        Nome
                        <i
                          class="fas fa-sort ms-2 text-muted"
                          [ngClass]="{
                            'fa-sort-up text-primary': sortColumn === 'name' && sortDirection === 'asc',
                            'fa-sort-down text-primary': sortColumn === 'name' && sortDirection === 'desc',
                          }"></i>
                      </div>
                    </th>
                    <th scope="col" class="text-end">Ações</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let serviceAdd of serviceAdds" [class.table-info]="isServiceAddInEdition(serviceAdd.id)">
                    <th scope="row" class="font-weight-bold">{{ serviceAdd.id }}</th>
                    <td>
                      <span [class.text-muted]="!serviceAdd.active">{{ serviceAdd.name }}</span>
                      <span *ngIf="!serviceAdd.active" class="badge bg-light text-muted ms-2">Inativo</span>
                    </td>
                    <td class="text-end">
                      <div class="d-flex justify-content-end gap-2 flex-wrap">
                        <button class="btn btn-sm btn-info text-white shadow-sm" (click)="edit(serviceAdd)" title="Editar">
                          <i class="fas fa-edit me-1"></i>
                          Editar
                        </button>

                        <button
                          *ngIf="!serviceAdd.active"
                          class="btn btn-sm btn-success shadow-sm"
                          (click)="activateServiceAdd(serviceAdd.id)"
                          title="Ativar">
                          <i class="fas fa-check me-1"></i>
                          Ativar
                        </button>

                        <app-confirm-modal
                          *ngIf="serviceAdd.active"
                          [btnClass]="'btn btn-sm btn-warning shadow-sm'"
                          [modalTitle]="'Inativar Serviço'"
                          [message]="'Tem certeza que deseja inativar o serviço ' + serviceAdd.name + '?'"
                          [okButtonLabel]="'Confirmar'"
                          (confirm)="deactivateServiceAdd(serviceAdd.id)">
                          <span modal-button>
                            <i class="fas fa-ban me-1"></i>
                            Inativar
                          </span>
                        </app-confirm-modal>

                        <app-confirm-modal
                          [btnClass]="'btn btn-sm btn-danger shadow-sm'"
                          [modalTitle]="'Excluir Serviço'"
                          [message]="'Ação irreversível! Deseja realmente excluir o serviço ' + serviceAdd.name + '?'"
                          [okButtonLabel]="'Excluir'"
                          (confirm)="deleteServiceAdd(serviceAdd.id)">
                          <span modal-button>
                            <i class="fas fa-trash me-1"></i>
                            Excluir
                          </span>
                        </app-confirm-modal>
                      </div>
                    </td>
                  </tr>
                  <tr *ngFor="let i of [1, 2, 3, 4, 5].slice(0, isLoader ? 5 : 0)">
                    <td colspan="3" class="text-center py-3">
                      <div class="placeholder-glow">
                        <span class="placeholder col-12 rounded"></span>
                      </div>
                    </td>
                  </tr>
                  <tr *ngIf="serviceAdds.length === 0 && !isLoader">
                    <td colspan="3" class="text-center py-5 text-muted">
                      <i class="fas fa-folder-open fa-3x mb-3 d-block opacity-25"></i>
                      Nenhum serviço adicional encontrado.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </app-datatable>
        </div>
      </div>
    </div>
  </div>
</app-authenticated-layout>

// resources/js/Pages/Auth/Auxiliaries/ServiceAdd.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import Modal from '@/Components/Modal.vue';
import Loader from '@/Components/Loader.vue';
import { Head, useForm } from '@inertiajs/inertia-vue3';
import { onMounted, ref } from 'vue';


const props = defineProps({
    services: Array
});

const inEdition = ref(0);

const form = useForm({
    id: 0,
    name: '',
});

const formDelete = useForm({
    id: 0
});


onMounted(() => {

    $('table').DataTable({
        language: {
            url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/pt-BR.json',
        },
    });
});

const isLoader = ref(false);

const deleteService = (id) => {
    isLoader.value = true;
    formDelete.id = id;
    formDelete.delete(route('service-add-delete'), {
        onFinish: () => {
            isLoader.value = false;
            formDelete.reset();
        },
    });
};

const edit = (service) => {
    inEdition.value = service.id;
    form.name = service.name;
    form.id = service.id;
};

const submit = () => {
    form.post(route('service-add-save'), {
        onSuccess: () => {
            form.reset();
            inEdition.value = 0;
        },
    });
};

const activate = (id) => {
    isLoader.value = true;
    form.put(route('service_adds-activate', id), {
        onFinish: () => {
            isLoader.value = false;
        },
    });
};

const deactivate = (id) => {
    isLoader.value = true;
    form.put(route('service_adds-deactivate', id), {
        onFinish: () => {
            isLoader.value = false;
        },
    });
};
</script>

<template>
    <AuthenticatedLayout>
        <Loader v-bind:show="isLoader"></Loader>

        <Head title="Serviços" />
        <template #header>
            <div class="d-sm-flex align-items-center justify-content-between">
                <h1 class="h3 mb-0 text-gray-800">Serviços</h1>
            </div>
        </template>
        <div class="row">
            <div class="col-lg-12">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="card mb-4 py-3 border-left-primary">
                            <div class="card-body">

                                <form @submit.prevent="submit">

                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <InputLabel for="name" value="Nome:" />
                                                <TextInput type="text" class="form-control" v-model="form.name" required
                                                    autofocus autocomplete="name" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.name" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="flex items-center justify-end mt-4 rigth">
                                        <PrimaryButton css-class="btn btn-primary float-right m-1"
                                            :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                            <span v-if="form.processing" class="spinner-border spinner-border-sm"
                                                role="status" aria-hidden="true"></span>
                                            Salvar
                                        </PrimaryButton>
                                        <PrimaryButton v-if="inEdition > 0" css-class="btn btn-info float-right m-1"
                                            v-on:click="form.reset(); inEdition = 0;"
                                            :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                            Novo
                                        </PrimaryButton>
                                    </div>

                                </form>
                            </div>
                        </div>

                    </div>

                    <div class="col-lg-12">
                        <div class="card mb-4 py-3 border-left-secondary">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Nome</th>
                                                <th scope="col">Ações</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr v-for="(service, index) in services"
                                                :class="{ 'table-info': inEdition == service.id }">
                                                <th scope="row">{{ service.id }}</th>
                                                <td>{{ service.name }}</td>
                                                <td>
                                                    <button class="btn btn-sm btn-info btn-icon-split mr-2"
                                                        v-on:click="edit(service)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-edit"></i>
                                                        </span>
                                                        <span class="text">Editar</span>
                                                    </button>

                                                    <Modal :key="index"
                                                        :modal-title="'Confirmar Exclusão de ' + service.name"
                                                        :ok-botton-callback="deleteService"
                                                        :ok-botton-callback-param="service.id"
                                                        btn-class="btn  btn-sm btn-danger btn-icon-split mr-2">
                                                        <template v-slot:button>
                                                            <span class="icon text-white-50">
                                                                <i class="fas fa-trash"></i>
                                                            </span>
                                                            <span class="text">Excluir</span>
                                                        </template>
                                                        <template v-slot:content>
                                                            Tem certeza que deseja apagar esse registro?
                                                        </template>
                                                    </Modal>


                                                    <button v-if="!service.active"
                                                        class="btn btn-sm btn-success btn-icon-split mr-2"
                                                        v-on:click="activate(service.id)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-check"></i>
                                                        </span>
                                                        <span class="text">Ativar</span>
                                                    </button>

                                                    <button v-if="service.active"
                                                        class="btn btn-sm btn-warning btn-icon-split mr-2"
                                                        v-on:click="deactivate(service.id)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-ban"></i>
                                                        </span>
                                                        <span class="text">Inativar</span>
                                                    </button>

                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </AuthenticatedLayout>
</template>
