// resources/js/Components/NavBar.vue
<script setup>
import ApplicationLogo from '@/Components/ApplicationLogo.vue';
import { Link } from '@inertiajs/inertia-vue3';

const imgProfile = new URL('/resources/images/undraw_profile.svg', import.meta.url).href

</script>


<template>
    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <ApplicationLogo style="max-height: 115px;"></ApplicationLogo>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">


            <!-- Nav Item - Alerts -->
            <!-- <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell fa-fw"></i>-->
            <!-- Counter - Alerts -->
            <!--<span class="badge badge-danger badge-counter">3+</span>
                </a>-->
            <!-- Dropdown - Alerts -->
            <!--<div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                    aria-labelledby="alertsDropdown">
                    <h6 class="dropdown-header">
                        Alerts Center
                    </h6>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="mr-3">
                            <div class="icon-circle bg-primary">
                                <i class="fas fa-file-alt text-white"></i>
                            </div>
                        </div>
                        <div>
                            <div class="small text-gray-500">December 12, 2019</div>
                            <span class="font-weight-bold">A new monthly report is ready to download!</span>
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="mr-3">
                            <div class="icon-circle bg-success">
                                <i class="fas fa-donate text-white"></i>
                            </div>
                        </div>
                        <div>
                            <div class="small text-gray-500">December 7, 2019</div>
                            $290.29 has been deposited into your account!
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="mr-3">
                            <div class="icon-circle bg-warning">
                                <i class="fas fa-exclamation-triangle text-white"></i>
                            </div>
                        </div>
                        <div>
                            <div class="small text-gray-500">December 2, 2019</div>
                            Spending Alert: We've noticed unusually high spending for your account.
                        </div>
                    </a>
                    <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                </div>
            </li> -->

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ $page.props.auth.user.name }}</span>
                    <img class="img-profile rounded-circle" :src="imgProfile">
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                    <Link class="dropdown-item" :href="route('profile')">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Perfil
                    </Link>
                    <div class="dropdown-divider"></div>
                    <Link class="dropdown-item" :href="route('logout')">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Sair
                    </Link>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->
</template>

// frontend/src/app/shared/components/navbar/navbar.component.ts
import { Component, inject, ElementRef, HostListener, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../../services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
  authService = inject(AuthService);
  el = inject(ElementRef);
  user = this.authService.user;

  toggleSidebar = output<void>();

  public isUserMenuOpen = false;
  public imgProfile = 'images/undraw_profile.svg';

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent) {
    // Se o clique for fora do componente, fecha o menu
    if (!this.el.nativeElement.contains(event.target)) {
      this.isUserMenuOpen = false;
    }
  }

  public toggleUserMenu() {
    this.isUserMenuOpen = !this.isUserMenuOpen;
  }

  public logout() {
    this.authService.logout();
  }
}

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow" style="height: 70px; padding-top: 0; padding-bottom: 0;">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3" (click)="toggleSidebar.emit()">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Logo placeholder or search -->
    <div class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 mw-100 d-flex align-items-center" style="overflow: hidden;">
        <img src="/logo.png" style="max-height: 120px; object-fit: contain;" alt="Logo">
    </div>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow" [class.show]="isUserMenuOpen">
            <a class="nav-link dropdown-toggle d-flex align-items-center" href="javascript:void(0)" id="userDropdown" role="button" (click)="toggleUserMenu()">
                <img class="img-profile rounded-circle mr-2" [src]="imgProfile" style="height: 2rem; width: 2rem;">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user()?.name }}</span>
                <!-- <i class="fas fa-caret-down fa-sm fa-fw text-gray-400"></i> -->
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" [class.show]="isUserMenuOpen" aria-labelledby="userDropdown" style="right: 0; left: auto;">
                <a class="dropdown-item" routerLink="/profile">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Perfil
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="javascript:void(0)" (click)="logout()">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Sair
                </a>
            </div>
        </li>

    </ul>

</nav>
