// resources/js/Components/Menu.vue
<script setup>
import { Link } from '@inertiajs/inertia-vue3';
const props = defineProps({
    //! Menu settings
    menuTitle: {
        type: String,
        default: '',
    },
    //! Menu items
    menuItems: {
        type: Array,
        default: () => [
            {
                link: '#',
                name: 'Inicio',
                icon: 'fa-solid fa-house',
                active: true,
                isItem: true
            },

        ],
    }
});

</script>


<template>
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <Link class="sidebar-brand d-flex align-items-center justify-content-center">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">{{ menuTitle }}</div>
        </Link>

        <li v-for="(menuItem, index) in menuItems" :key="index" :class="{ 'active': menuItem.active }" class="nav-item">

            <hr v-if="menuItem.divider" class="sidebar-divider d-none d-md-block">
            <!-- Nav Item -->
            <Link v-if="menuItem.isItem" class="nav-link" :href="menuItem.link">
            <i :class="menuItem.icon || 'fa-solid fa-check'"></i>
            <span>{{ menuItem.name }}</span>
            </Link>

            <!-- Nav Item - Collapse Menu -->
            <a v-if="!menuItem.isItem && menuItem.subMenu.some((s) => $page.props.auth.permissions.some((p) => p.name === s.role || (Array.isArray(s.role) && s.role.some((r) => r == p.name))))"
                class="nav-link collapsed" href="#" data-toggle="collapse" :data-target="'#collapse1' + index"
                aria-expanded="true" :aria-controls="'collapse1' + index">
                <i :class="menuItem.icon || 'fa-solid fa-check'"></i>
                <span>{{ menuItem.name }}</span>
            </a>
            <div v-if="!menuItem.isItem" :id="'collapse1' + index" class="collapse"
                :class="{ 'show': menuItem.subMenu.some((s) => s.active) }" aria-labelledby="headingTwo"
                style="visibility: inherit" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">{{ menuItem.collapseHeader }}:</h6>
                    <Link
                        v-for="(subMenuItem, subIndex) in menuItem.subMenu.filter((s) => $page.props.auth.permissions.some((p) => p.name === s.role || (Array.isArray(s.role) && s.role.some((r) => r == p.name))))"
                        :key="subIndex" class="collapse-item" :href="subMenuItem.link"
                        :class="{ 'active': subMenuItem.active }">
                    {{ subMenuItem.name }}
                    </Link>
                </div>
            </div>
        </li>


        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->
</template>

// frontend/src/app/shared/components/menu/menu.component.ts
import { Component, computed, inject, signal, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../../services/auth.service';

interface SubMenuItem {
  link: string;
  name: string;
  active?: boolean;
  role: string | string[];
}

interface MenuItem {
  name: string;
  icon: string;
  isItem: boolean;
  link?: string;
  active?: boolean;
  collapseHeader?: string;
  subMenu?: SubMenuItem[];
  divider?: boolean;
  collapsed?: boolean;
}

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.scss']
})
export class MenuComponent {
  private readonly authService = inject(AuthService);
  
  isToggled = input<boolean>(false);
  toggleSidebar = output<void>();

  menuTitle = 'SmartApp';
  userPermissions = computed(() => this.authService.user()?.permissions || []);

  menuItems: MenuItem[] = [
    {
      link: '/dashboard',
      name: 'Inicio',
      icon: 'fas fa-fw fa-home',
      isItem: true,
    },
    {
      name: 'Usuários',
      icon: 'fas fw fa-users',
      isItem: false,
      collapseHeader: 'Administrar acessos',
      collapsed: true,
      subMenu: [
        { link: '/role', name: 'Grupo de Acesso', role: 'role_admin' },
        { link: '/register', name: 'Usuário', role: 'user_admin' }
      ],
    },
    {
      name: 'Hotel',
      icon: 'fa fa-bed',
      isItem: false,
      collapseHeader: 'Tabelas auxiliares',
      collapsed: true,
      subMenu: [
        { link: '/broker', name: 'Broker', role: 'broker_admin' },
        { link: '/regime', name: 'Regime', role: 'regime_admin' },
        { link: '/purpose', name: 'Propósito', role: 'purpose_admin' },
        { link: '/category', name: 'Categoria', role: 'category_admin' },
        { link: '/apto', name: 'Apartamento', role: 'apto_admin' },
        { link: '/hotel', name: 'Hotel', role: 'admin_provider' },
      ]
    },
    {
      name: 'A&B',
      icon: 'fa fa-utensils',
      isItem: false,
      collapseHeader: 'Tabelas auxiliares',
      collapsed: true,
      subMenu: [
        { link: '/service', name: 'Serviço', role: 'service_admin' },
        { link: '/service-type', name: 'Tipo de Serviço', role: 'service_type_admin' },
        { link: '/local', name: 'Local', role: 'local_admin' },
      ]
    },
    {
      name: 'Salões',
      icon: 'fa fa-warehouse',
      isItem: false,
      collapseHeader: 'Tabelas auxiliares',
      collapsed: true,
      subMenu: [
        { link: '/service-hall', name: 'Serviço', role: 'service_hall_admin' },
        { link: '/purpose-hall', name: 'Propósito', role: 'purpose_hall_admin' },
      ]
    },
    {
      name: 'Adicionais',
      icon: 'fa fa-stream',
      isItem: false,
      collapseHeader: 'Tabelas auxiliares',
      collapsed: true,
      subMenu: [
        { link: '/service-add', name: 'Serviços', role: 'service_add_admin' },
        { link: '/measure', name: 'Medida', role: 'measure_admin' },
        { link: '/frequency', name: 'Frequência', role: 'frequency_admin' },
        { link: '/provider-service', name: 'Fornecedor', role: 'admin_provider_service' },
      ]
    },
    {
      name: 'Transporte',
      icon: 'fa fa-car-alt',
      isItem: false,
      collapseHeader: 'Tabelas auxiliares',
      collapsed: true,
      subMenu: [
        { link: '/broker-trans', name: 'Broker', role: 'broker_trans_admin' },
        { link: '/brand', name: 'Marca', role: 'brand_admin' },
        { link: '/car-model', name: 'Modelo de Carro', role: 'car_model_admin' },
        { link: '/vehicle', name: 'Tipo de Veículo', role: 'vehicle_admin' },
        { link: '/transport-service', name: 'Serviços', role: 'transport_service_admin' },
        { link: '/provider-transport', name: 'Fornecedor', role: 'admin_provider_transport' },
      ]
    },
    {
      name: 'Administrativo',
      icon: 'fa fa-user-cog',
      isItem: false,
      collapseHeader: 'Tabelas auxiliares',
      collapsed: true,
      subMenu: [
        { link: '/currency', name: 'Moeda', role: 'currency_admin' },
        { link: '/customer', name: 'Clientes', role: 'customer_admin' },
        { link: '/crd', name: 'CRD\'s', role: 'crd_admin' },
        { link: '/city', name: 'Cidade', role: 'city_admin' },
      ]
    },
    {
      name: 'Eventos',
      icon: 'fa fa-calendar-check',
      isItem: false,
      collapseHeader: 'Cotações',
      collapsed: true,
      subMenu: [
        { link: '/event-create', name: 'Cadastro Inicial', role: 'event_admin' },
        { link: '/event-list', name: 'Listar', role: ['event_admin', 'hotel_operator', 'land_operator', 'air_operator'] }
      ],
    },
  ];

  hasPermission(role: string | string[]): boolean {
    const permissions = this.userPermissions();
    if (!permissions || permissions.length === 0) return false;
    const roles = Array.isArray(role) ? role : [role];
    return roles.some(r => permissions.some(p => p.name === r));
  }

  canShowMenu(menuItem: MenuItem): boolean {
    if (menuItem.isItem) return true;
    if (!menuItem.subMenu) return false;
    return menuItem.subMenu.some(s => this.hasPermission(s.role));
  }

  toggleCollapse(menuItem: MenuItem) {
    const isExpanding = menuItem.collapsed;
    
    if (isExpanding) {
      // Fecha todos os outros antes de abrir o atual
      this.menuItems.forEach(item => {
        if (!item.isItem) {
          item.collapsed = true;
        }
      });
    }
    
    menuItem.collapsed = !menuItem.collapsed;
  }

  isAngularRoute(link: string | undefined): boolean {
    if (!link) return false;
    const angularRoutes = ['/dashboard', '/apto'];
    return angularRoutes.includes(link);
  }
}

<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar" [class.toggled]="isToggled()">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" routerLink="/dashboard">
        <div class="sidebar-brand-icon">
            <i class="fas fa-building"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SmartApp</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <ng-container *ngFor="let menuItem of menuItems; let i = index">
        <li *ngIf="canShowMenu(menuItem)" class="nav-item" [class.active]="menuItem.active">
            
            <hr *ngIf="menuItem.divider" class="sidebar-divider d-none d-md-block opacity-25">

            <!-- Nav Item -->
            <a *ngIf="menuItem.isItem" class="nav-link" [routerLink]="menuItem.link" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
                <i [class]="menuItem.icon || 'fa-solid fa-check'"></i>
                <span>{{ menuItem.name }}</span>
            </a>

            <!-- Nav Item - Collapse Menu -->
            <a *ngIf="!menuItem.isItem" class="nav-link" 
               [class.collapsed]="menuItem.collapsed" 
               href="javascript:void(0)"
               (click)="toggleCollapse(menuItem)"
               data-toggle="collapse"
               [attr.aria-expanded]="!menuItem.collapsed">
                <i [class]="menuItem.icon || 'fa-solid fa-check'"></i>
                <span>{{ menuItem.name }}</span>
            </a>
            
            <div *ngIf="!menuItem.isItem" class="collapse" [class.show]="!menuItem.collapsed" style="visibility: inherit">
                <div class="bg-white py-2 collapse-inner rounded shadow-lg">
                    <h6 class="collapse-header">{{ menuItem.collapseHeader }}:</h6>
                    <ng-container *ngFor="let subMenuItem of menuItem.subMenu">
                        <!-- Angular Link -->
                        <a *ngIf="hasPermission(subMenuItem.role) && isAngularRoute(subMenuItem.link)" 
                           class="collapse-item" 
                           [routerLink]="subMenuItem.link"
                           routerLinkActive="active"
                           [class.active]="subMenuItem.active">
                            {{ subMenuItem.name }}
                        </a>
                        
                        <!-- Vue Link (Full Page Reload) -->
                        <a *ngIf="hasPermission(subMenuItem.role) && !isAngularRoute(subMenuItem.link)" 
                           class="collapse-item" 
                           [href]="subMenuItem.link"
                           [class.active]="subMenuItem.active">
                            {{ subMenuItem.name }}
                        </a>
                    </ng-container>
                </div>
            </div>
        </li>
    </ng-container>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block opacity-25 mt-3">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline pt-4">
        <button class="rounded-circle border-0 shadow-sm" id="sidebarToggle" (click)="toggleSidebar.emit()"></button>
    </div>

</ul>
