// frontend/src/app/pages/forgot-password/forgot-password.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { RouterLink } from '@angular/router';
import { ToastService } from '../../services/toast.service';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-forgot-password',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './forgot-password.component.html',
  styleUrls: ['./forgot-password.component.scss']
})
export class ForgotPasswordComponent {
  private readonly http: HttpClient = inject(HttpClient);
  private readonly toastService: ToastService = inject(ToastService);
  private readonly apiUrl = environment.apiUrl;

  email: string = '';
  status: string | null = null;
  errors: any = {};
  processing = false;

  submit() {
    this.processing = true;
    this.errors = {};
    this.status = null;

    this.http.get(`${this.apiUrl}/sanctum/csrf-cookie`).subscribe({
      next: () => {
        this.http.post(`${this.apiUrl}/forgot-password`, { email: this.email }).subscribe({
          next: (response: any) => {
            this.processing = false;
            this.status = response.status;
            this.toastService.success(this.status || 'Link de redefinição enviado!');
            this.email = '';
          },
          error: (err: HttpErrorResponse) => {
            this.processing = false;
            if (err.status === 422) {
              this.errors = err.error.errors;
            } else if (err.error && err.error.message) {
              this.toastService.error(err.error.message);
            } else {
              this.toastService.error('Ocorreu um erro ao processar sua solicitação.');
            }
          }
        });
      },
      error: (err: HttpErrorResponse) => {
        this.processing = false;
        console.error('CSRF setup failed', err);
      }
    });
  }
}

<div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
    <div>
        <a href="/">
            <img src="/logo.png" alt="SmartApp Logo" class="w-20 h-20 object-contain">
        </a>
    </div>

    <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
        
        <div class="mb-4 text-sm text-gray-600">
            Esqueceu sua senha? Sem problemas. Basta nos informar seu endereço de e-mail e enviaremos um link de redefinição de senha que permitirá que você escolha uma nova.
        </div>

        <!-- Session Status -->
        <div *ngIf="status" class="mb-4 font-medium text-sm text-green-600">
            {{ status }}
        </div>

        <form #forgotForm="ngForm" (ngSubmit)="forgotForm.valid && submit()">
            <div>
                <label for="email" class="block font-medium text-sm text-gray-700">Email</label>
                <input id="email" type="email" #emailInput="ngModel"
                    class="border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md shadow-sm mt-1 block w-full" 
                    [(ngModel)]="email" name="email" required email autofocus autocomplete="username"
                    [class.border-red-500]="(emailInput.invalid && (emailInput.dirty || emailInput.touched)) || forgotForm.submitted">
                
                <div *ngIf="(emailInput.invalid && (emailInput.dirty || emailInput.touched)) || forgotForm.submitted" class="mt-1 text-xs text-red-500">
                    <span *ngIf="emailInput.errors?.['required']">O e-mail é obrigatório.</span>
                    <span *ngIf="emailInput.errors?.['email']">Insira um e-mail válido.</span>
                </div>
                <div *ngIf="errors.email" class="mt-2 text-sm text-red-600">{{ errors.email?.[0] }}</div>
            </div>

            <div class="flex items-center justify-between mt-4">
                <a routerLink="/login" class="underline text-sm text-gray-600 hover:text-gray-900">
                    Voltar para o login
                </a>

                <button type="submit" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring ring-gray-300 disabled:opacity-25 transition ease-in-out duration-150 ml-4" 
                    [ngClass]="{ 'opacity-25': processing || forgotForm.invalid }" [disabled]="processing">
                    Enviar Link de Redefinição
                </button>
            </div>
        </form>
    </div>
</div>

// resources/js/Pages/Auth/ForgotPassword.vue
<script setup>
import GuestLayout from '@/Layouts/GuestLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Head, useForm } from '@inertiajs/inertia-vue3';

defineProps({
    status: String,
});

const form = useForm({
    email: '',
});

const submit = () => {
    form.post(route('password.email'));
};
</script>

<template>
    <GuestLayout>

        <Head title="Recuperação de senha" />

        <div class="mb-4 text-sm text-gray-600">
            Esqueceu sua senha? Sem problemas. Basta nos informar seu endereço de e-mail e nós lhe enviaremos um link de
            redefinição de senha que permitirá que você escolha uma nova.
        </div>

        <div v-if="status" class="mb-4 font-medium text-sm text-green-600">
            {{ status }}
        </div>

        <form @submit.prevent="submit">
            <div>
                <InputLabel for="email" value="Email" />
                <TextInput id="email" type="email" class="mt-1 block w-full" v-model="form.email" required autofocus
                    autocomplete="username" />
                <InputError class="mt-2" :message="form.errors.email" />
            </div>

            <div class="flex items-center justify-end mt-4">
                <PrimaryButton :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Enviar link de recuperação de senha
                </PrimaryButton>
            </div>
        </form>
    </GuestLayout>
</template>
