// frontend/src/app/pages/user/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ProfileService } from '../../../services/profile.service';
import { ToastService } from '../../../services/toast.service';
import { AuthenticatedLayoutComponent } from '../../../shared/layouts/authenticated-layout/authenticated-layout.component';
import { QuillModule } from 'ngx-quill';
import { NgxMaskDirective } from 'ngx-mask';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule, AuthenticatedLayoutComponent, QuillModule, NgxMaskDirective],
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss']
})
export class ProfileComponent implements OnInit {
  profileForm: FormGroup;
  isLoader = false;
  processing = false;
  roles: any[] = [];
  
  quillModules = {
    toolbar: [
      ['bold', 'italic', 'underline', 'strike'],
      ['blockquote', 'code-block'],
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      [{ 'color': [] }, { 'background': [] }],
      ['link', 'image']
    ]
  };

  constructor(
    private profileService: ProfileService,
    private toastService: ToastService,
    private fb: FormBuilder
  ) {
    this.profileForm = this.fb.group({
      name: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      phone: ['', Validators.required],
      signature: ['']
    });
  }

  ngOnInit(): void {
    this.loadProfile();
  }

  loadProfile(): void {
    this.isLoader = true;
    this.profileService.getProfile().subscribe({
      next: (res) => {
        const user = res.user;
        this.profileForm.patchValue({
          name: user.name || '',
          email: user.email || '',
          phone: user.phone || '',
          signature: user.signature || ''
        });
        this.roles = user.roles || [];
        this.isLoader = false;
      },
      error: () => {
        this.isLoader = false;
        this.toastService.error('Erro ao carregar dados do perfil');
      }
    });
  }

  submit(): void {
    if (this.profileForm.invalid) return;
    this.processing = true;
    this.profileService.saveProfile(this.profileForm.value).subscribe({
      next: () => {
        this.toastService.success('Perfil salvo com sucesso');
        this.processing = false;
      },
      error: () => {
        this.processing = false;
        this.toastService.error('Erro ao salvar perfil');
      }
    });
  }
}

<app-authenticated-layout title="Meus Dados">
    <ng-container header>
        <div class="d-sm-flex align-items-center justify-content-between mb-4 animate-in">
            <h1 class="h3 mb-0 text-gray-800">Meus Dados</h1>
        </div>
    </ng-container>

    <div class="row position-relative">
        <div class="col-lg-12 animate-in" style="animation-delay: 0.1s;">
            <!-- Indicador de carregamento inicial -->
            <div *ngIf="isLoader" class="d-flex justify-content-center my-5">
                <div class="spinner-border text-primary" role="status">
                    <span class="visually-hidden">Carregando...</span>
                </div>
            </div>

            <div class="card mb-4 border-left-primary" *ngIf="!isLoader">
                <div class="card-body">
                    <h5 class="card-title mb-4 text-primary font-weight-bold">
                        <i class="fas fa-id-card me-2"></i>Informações do Perfil
                    </h5>
                    
                    <form [formGroup]="profileForm" (ngSubmit)="submit()">
                        <div class="row">
                            <div class="col-lg-4 mb-3">
                                <div class="form-group mb-0">
                                    <label for="name" class="form-label">Nome: <span class="text-danger">*</span></label>
                                    <input type="text" id="name" class="form-control" formControlName="name" placeholder="Ex: João Silva" required autofocus>
                                    <div *ngIf="profileForm.get('name')?.invalid && profileForm.get('name')?.touched" class="text-danger mt-1">
                                        <small>O nome é obrigatório</small>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="form-group mb-0">
                                    <label for="phone" class="form-label">Telefone: <span class="text-danger">*</span></label>
                                    <input type="text" id="phone" class="form-control" formControlName="phone" placeholder="Ex: (11) 99999-9999" mask="(00) 0000-00009" [dropSpecialCharacters]="false" required>
                                    <div *ngIf="profileForm.get('phone')?.invalid && profileForm.get('phone')?.touched" class="text-danger mt-1">
                                        <small>O telefone é obrigatório</small>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="form-group mb-0">
                                    <label for="email" class="form-label">E-mail: <span class="text-danger">*</span></label>
                                    <input type="email" id="email" class="form-control" formControlName="email" placeholder="exemplo@email.com" required>
                                    <div *ngIf="profileForm.get('email')?.invalid && profileForm.get('email')?.touched" class="text-danger mt-1">
                                        <small *ngIf="profileForm.get('email')?.errors?.['required']">O e-mail é obrigatório</small>
                                        <small *ngIf="profileForm.get('email')?.errors?.['email']">O e-mail informado não é válido</small>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-8 mb-3">
                                <div class="form-group mb-0">
                                    <label for="signature" class="form-label">Assinatura:</label>
                                    <quill-editor formControlName="signature" 
                                                  [modules]="quillModules" 
                                                  placeholder="Sua assinatura de email..."
                                                  [style]="{height: '150px'}"></quill-editor>
                                </div>
                            </div>

                            <div class="col-lg-4 mb-3">
                                <div class="form-group mb-0">
                                    <label class="form-label">Seus Grupos de Acesso (Somente Leitura):</label>
                                    <div class="card">
                                        <div class="card-body py-2" style="max-height: 190px; overflow-y: auto; background-color: #f8f9fa;">
                                            <div *ngIf="isLoader" class="text-center py-4">
                                                <div class="spinner-border text-primary spinner-border-sm" role="status"></div>
                                                <small class="d-block mt-2 text-muted">Carregando...</small>
                                            </div>
                                            <ng-container *ngIf="!isLoader">
                                                <div class="form-check" *ngFor="let role of roles">
                                                    <input class="form-check-input" type="checkbox"
                                                           [id]="'role_' + role.id"
                                                           checked
                                                           disabled>
                                                    <label class="form-check-label text-muted" [for]="'role_' + role.id">
                                                        {{ role.name }}
                                                    </label>
                                                </div>
                                                <div *ngIf="roles.length === 0" class="text-muted small mt-1">
                                                    <i class="fas fa-info-circle me-1"></i> Nenhum grupo atribuído.
                                                </div>
                                            </ng-container>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row mt-3">
                            <div class="col-12 d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary shadow-sm" [disabled]="profileForm.invalid || processing" [class.opacity-50]="processing">
                                    <span *ngIf="processing" class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
                                    <i *ngIf="!processing" class="fas fa-save me-1"></i>
                                    Salvar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</app-authenticated-layout>

// resources/js/Pages/Auth/Profile.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Head, useForm } from '@inertiajs/inertia-vue3';
import { onMounted } from 'vue';
import CKEditor from '@/Components/CKEditor.vue';


const props = defineProps({
    user: Array,
});

const form = useForm({
    id: 0,
    name: '',
    email: '',
    phone: '',
    signature: '',
});

const submit = () => {
    form.post(route('profile'), {
        onFinish: () => form.reset('password', 'password_confirmation'),
    });
};

onMounted(() => {
    if (props.user != null) {
        form.id = props.user.id;
        form.name = props.user.name;
        form.phone = props.user.phone;
        form.email = props.user.email;
        form.signature = props.user.signature;
    }

    $('#phone').mask('(00) 00000-0000');
});

</script>

<template>
    <AuthenticatedLayout>

        <Head title="Editar Perfil" />

        <template #header>
            <div class="d-sm-flex align-items-center justify-content-between">
                <h1 class="h3 mb-0 text-gray-800">Meus Dados</h1>
            </div>
        </template>

        <div class="row">
            <div class="col-lg-12">
                <div class="card mb-4 py-3 border-left-primary">
                    <div class="card-body">
                        <form @submit.prevent="submit">

                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <InputLabel for="name" value="Name" />
                                                <TextInput id="name" type="text" class="form-control"
                                                    v-model="form.name" required autofocus autocomplete="name" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.name" />
                                            </div>
                                            <div class="form-group">
                                                <InputLabel for="Phone" value="Telefone" />
                                                <TextInput id="phone" type="text" class="form-control"
                                                    v-model="form.phone" required autofocus autocomplete="phone" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.phone" />
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">

                                                <InputLabel for="email" value="Email" />
                                                <TextInput id="email" type="email" class="form-control"
                                                    v-model="form.email" required autocomplete="username" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.email" />
                                            </div>

                                            <div class="form-group">
                                                <InputLabel for="signature" value="Assinatura" />
                                                <CKEditor v-model:content="form.signature" :height="150" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.signature" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <ul class="list-group">
                                        <li v-for="(role, key) in user.roles"
                                            class="list-group-item d-flex justify-content-between align-items-center">
                                            {{ role.name }}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="flex items-center justify-end mt-4">

                                <PrimaryButton css-class="btn btn-primary float-right m-1"
                                    :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                    <span v-if="form.processing" class="spinner-border spinner-border-sm" role="status"
                                        aria-hidden="true"></span>
                                    Salvar
                                </PrimaryButton>

                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </AuthenticatedLayout>
</template>
