// frontend/src/app/pages/regime/regime.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';

import { RegimeService, Regime, RegimeCreateUpdateRequest } from '../../services/regime.service';
import { ToastService } from '../../services/toast.service';
import { AuthenticatedLayoutComponent } from "../../shared/layouts/authenticated-layout/authenticated-layout.component";
import { ConfirmModalComponent } from "../../shared/components/confirm-modal/confirm-modal.component";
import { DatatableComponent } from "../../shared/components/datatable/datatable.component";

@Component({
  selector: 'app-regime',
  standalone: true,
  imports: [CommonModule, FormsModule, AuthenticatedLayoutComponent, ConfirmModalComponent, DatatableComponent],
  templateUrl: './regime.component.html',
  styleUrls: ['./regime.component.scss']
})
export class RegimeComponent implements OnInit {
  private readonly regimeService: RegimeService = inject(RegimeService);
  private readonly toastService: ToastService = inject(ToastService);

  regimes: Regime[] = [];
  inEdition: number = 0;
  isLoader: boolean = false;
  processing: boolean = false;
  errors: any = {};

  // Pagination and Filtering state
  pagination: any = {
    current_page: 1,
    per_page: 20,
    total: 0,
    last_page: 1,
    from: 0,
    to: 0
  };
  searchQuery: string = '';
  sortColumn: string = 'id';
  sortDirection: string = 'desc';

  form = {
    id: 0,
    name: ''
  };

  ngOnInit(): void {
    this.loadRegimes();
  }

  /**
   * Carregar lista de regimes com paginação e filtros
   */
  loadRegimes(): void {
    this.isLoader = true;
    const params = {
      page: this.pagination.current_page,
      per_page: this.pagination.per_page,
      search: this.searchQuery,
      sort_column: this.sortColumn,
      sort_direction: this.sortDirection
    };

    this.regimeService.getRegimes(params).subscribe({
      next: (response: any) => {
        this.regimes = response.data || [];
        this.pagination = {
          current_page: response.current_page,
          per_page: response.per_page,
          total: response.total,
          last_page: response.last_page,
          from: response.from,
          to: response.to
        };
        this.isLoader = false;
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao carregar regimes');
        console.error('Erro ao carregar regimes:', error);
      }
    });
  }

  /**
   * Pesquisar (chamado pelo DatatableComponent)
   */
  onSearch(query: string): void {
    this.searchQuery = query;
    this.pagination.current_page = 1;
    this.loadRegimes();
  }

  /**
   * Mudar página (chamado pelo DatatableComponent)
   */
  onPageChange(page: number): void {
    this.pagination.current_page = page;
    this.loadRegimes();
  }

  /**
   * Mudar quantidade por página (chamado pelo DatatableComponent)
   */
  onPerPageChange(perPage: number): void {
    this.pagination.per_page = perPage;
    this.pagination.current_page = 1;
    this.loadRegimes();
  }

  /**
   * Ordenar coluna
   */
  sortBy(column: string): void {
    if (this.sortColumn === column) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortColumn = column;
      this.sortDirection = 'asc';
    }
    this.loadRegimes();
  }

  /**
   * Editar regime
   */
  edit(regime: Regime): void {
    this.inEdition = regime.id;
    this.form.id = regime.id;
    this.form.name = regime.name;
    this.errors = {};
  }

  /**
   * Cancelar edição
   */
  cancelEdit(): void {
    this.inEdition = 0;
    this.resetForm();
  }

  /**
   * Resetar formulário
   */
  resetForm(): void {
    this.form = {
      id: 0,
      name: ''
    };
    this.errors = {};
    this.inEdition = 0;
  }

  /**
   * Validar formulário
   */
  private validateForm(): boolean {
    this.errors = {};

    if (!this.form.name || this.form.name.trim() === '') {
      this.errors.name = ['O nome é obrigatório'];
      return false;
    }

    return true;
  }

  /**
   * Salvar regime (criar ou atualizar)
   */
  submit(): void {
    if (!this.validateForm()) {
      return;
    }

    this.processing = true;

    const data: RegimeCreateUpdateRequest = {
      id: this.form.id,
      name: this.form.name
    };

    this.regimeService.saveRegime(data).subscribe({
      next: (response: any) => {
        this.processing = false;
        this.toastService.success(response.message || 'Regime salvo com sucesso');
        this.resetForm();
        this.loadRegimes();
      },
      error: (error: HttpErrorResponse) => {
        this.processing = false;
        if (error.status === 422) {
          this.errors = error.error.errors || {};
        } else {
          this.toastService.error('Erro ao salvar regime');
        }
        console.error('Erro ao salvar regime:', error);
      }
    });
  }

  /**
   * Deletar regime
   */
  deleteRegime(regimeId: number): void {
    this.isLoader = true;
    this.regimeService.deleteRegime(regimeId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Regime apagado com sucesso');
        this.loadRegimes();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao apagar regime');
        console.error('Erro ao deletar regime:', error);
      }
    });
  }

  /**
   * Ativar regime
   */
  activateRegime(regimeId: number): void {
    this.isLoader = true;
    this.regimeService.activateRegime(regimeId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Regime ativado com sucesso');
        this.loadRegimes();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao ativar regime');
        console.error('Erro ao ativar regime:', error);
      }
    });
  }

  /**
   * Inativar regime
   */
  deactivateRegime(regimeId: number): void {
    this.isLoader = true;
    this.regimeService.deactivateRegime(regimeId).subscribe({
      next: (response: any) => {
        this.isLoader = false;
        this.toastService.success(response.message || 'Regime inativado com sucesso');
        this.loadRegimes();
      },
      error: (error: HttpErrorResponse) => {
        this.isLoader = false;
        this.toastService.error('Erro ao inativar regime');
        console.error('Erro ao inativar regime:', error);
      }
    });
  }

  /**
   * Método auxiliar para template
   */
  isRegimeInEdition(regimeId: number): boolean {
    return this.inEdition === regimeId;
  }
}

<app-authenticated-layout title="Regime">
    <ng-container header>
        <div class="d-sm-flex align-items-center justify-content-between">
            <h1 class="h3 mb-0 text-gray-800">Regime</h1>
        </div>
    </ng-container>

    <div class="row position-relative">
        <!-- Form Section -->
        <div class="col-lg-12">
            <div class="card mb-4 py-3 border-left-primary">
                <div class="card-body">
                    <form (ngSubmit)="submit()">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="name" class="form-label">Nome:</label>
                                    <input 
                                        type="text" 
                                        id="name" 
                                        class="form-control" 
                                        [(ngModel)]="form.name" 
                                        name="name" 
                                        required 
                                        autofocus>
                                    
                                    <div *ngIf="errors['name']" class="text-danger mt-1">
                                        <small *ngFor="let err of errors['name']">{{ err }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="d-flex align-items-center justify-content-end mt-4">
                            <button 
                                type="submit" 
                                class="btn btn-primary m-1" 
                                [disabled]="processing" 
                                [class.opacity-50]="processing">
                                <span *ngIf="processing" class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
                                Salvar
                            </button>

                            <button 
                                type="button" 
                                *ngIf="inEdition > 0" 
                                class="btn btn-info m-1 text-white" 
                                (click)="resetForm()"
                                [disabled]="processing">
                                Novo
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- Table Section -->
        <div class="col-lg-12">
                <div class="card mb-4 py-3 border-left-secondary">
                    <div class="card-body">
                        <app-datatable 
                            [pagination]="pagination" 
                            [loading]="isLoader"
                            (search)="onSearch($event)"
                            (pageChange)="onPageChange($event)"
                            (perPageChange)="onPerPageChange($event)">
                            
                            <table class="table table-striped table-hover" width="100%" cellspacing="0">
                                <thead class="table-light">
                                    <tr>
                                        <th scope="col" (click)="sortBy('id')" style="cursor: pointer;">
                                            <i class="fas fa-sort me-1 text-muted mt-1" [ngClass]="{'fa-sort-up': sortColumn === 'id' && sortDirection === 'asc', 'fa-sort-down': sortColumn === 'id' && sortDirection === 'desc'}"></i> #
                                        </th>
                                        <th scope="col" (click)="sortBy('name')" style="cursor: pointer;">
                                            <i class="fas fa-sort me-1 text-muted mt-1" [ngClass]="{'fa-sort-up': sortColumn === 'name' && sortDirection === 'asc', 'fa-sort-down': sortColumn === 'name' && sortDirection === 'desc'}"></i> Nome
                                        </th>
                                        <th scope="col">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr *ngFor="let regime of regimes" [class.table-info]="isRegimeInEdition(regime.id)">
                                        <th scope="row">{{ regime.id }}</th>
                                        <td>{{ regime.name }}</td>
                                        <td>
                                            <!-- Editar -->
                                            <button class="btn btn-sm btn-info btn-icon-split me-2 mb-1" (click)="edit(regime)" title="Editar">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-edit"></i>
                                                </span>
                                                <span class="text">Editar</span>
                                            </button>

                                            <!-- Deletar -->
                                            <app-confirm-modal 
                                                [btnClass]="'btn btn-sm btn-danger btn-icon-split me-2 mb-1'" 
                                                [modalTitle]="'Atenção'" 
                                                [message]="'Tem certeza que deseja apagar esse registro?'"
                                                [okButtonLabel]="'Confirmar'"
                                                (confirm)="deleteRegime(regime.id)">
                                                <span modal-button class="icon text-white-50">
                                                    <i class="fas fa-trash"></i>
                                                </span>
                                                <span modal-button class="text">Excluir</span>
                                            </app-confirm-modal>

                                            <!-- Ativar -->
                                            <button *ngIf="!regime.active" class="btn btn-sm btn-success btn-icon-split me-2 mb-1" (click)="activateRegime(regime.id)" title="Ativar">
                                                <span class="icon text-white-50">
                                                    <i class="fas fa-check"></i>
                                                </span>
                                                <span class="text">Ativar</span>
                                            </button>

                                            <!-- Inativar -->
                                            <app-confirm-modal 
                                                *ngIf="regime.active"
                                                [btnClass]="'btn btn-sm btn-warning btn-icon-split me-2 mb-1'" 
                                                [modalTitle]="'Atenção'" 
                                                [message]="'Tem certeza que deseja inativar esse registro?'"
                                                [okButtonLabel]="'Confirmar'"
                                                (confirm)="deactivateRegime(regime.id)">
                                                <span modal-button class="icon text-white-50">
                                                    <i class="fas fa-ban"></i>
                                                </span>
                                                <span modal-button class="text">Inativar</span>
                                            </app-confirm-modal>
                                        </td>
                                    </tr>
                                    <tr *ngIf="regimes.length === 0 && !isLoader">
                                        <td colspan="3" class="text-center py-4 text-muted">
                                            Nenhum regime encontrado.
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </app-datatable>
                    </div>
                </div>
        </div>
    </div>
</app-authenticated-layout>

// resources/js/Pages/Auth/Regime.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import Modal from '@/Components/Modal.vue';
import Loader from '@/Components/Loader.vue';
import { Head, useForm } from '@inertiajs/inertia-vue3';
import { onMounted, ref } from 'vue';


const props = defineProps({
    regimes: Array
});

const inEdition = ref(0);

const form = useForm({
    id: 0,
    name: '',
});

const formDelete = useForm({
    id: 0
});


onMounted(() => {

    $('table').DataTable({
        language: {
            url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/pt-BR.json',
        },
    });
});

const isLoader = ref(false);

const deleteRegime = (id) => {
    isLoader.value = true;
    formDelete.id = id;
    formDelete.delete(route('regime-delete'), {
        onFinish: () => {
            isLoader.value = false;
            formDelete.reset();
        },
    });
};

const edit = (regime) => {
    inEdition.value = regime.id;
    form.name = regime.name;
    form.id = regime.id;
};

const submit = () => {
    form.post(route('regime-save'), {
        onSuccess: () => {
            form.reset();
            inEdition.value = 0;
        },
    });
};
</script>

<template>
    <AuthenticatedLayout>
        <Loader v-bind:show="isLoader"></Loader>

        <Head title="Regime" />
        <template #header>
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Regime</h1>
            </div>
        </template>
        <div class="row">
            <div class="col-lg-12">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="card mb-4 py-3 border-left-primary">
                            <div class="card-body">

                                <form @submit.prevent="submit">

                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <InputLabel for="name" value="Nome:" />
                                                <TextInput type="text" class="form-control" v-model="form.name" required
                                                    autofocus autocomplete="name" />
                                                <InputError class="mt-2 text-danger" :message="form.errors.name" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="flex items-center justify-end mt-4 rigth">
                                        <PrimaryButton css-class="btn btn-primary float-right"
                                            :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                            <span v-if="form.processing" class="spinner-border spinner-border-sm"
                                                role="status" aria-hidden="true"></span>
                                            Salvar
                                        </PrimaryButton>
                                        <PrimaryButton v-if="inEdition > 0" css-class="btn btn-info float-right m-1"
                                            v-on:click="form.reset(); inEdition = 0;"
                                            :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                            Novo
                                        </PrimaryButton>
                                    </div>

                                </form>
                            </div>
                        </div>

                    </div>

                    <div class="col-lg-12">
                        <div class="card mb-4 py-3 border-left-secondary">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th scope="col">#</th>
                                                <th scope="col">Nome</th>
                                                <th scope="col">Ações</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr v-for="(regime, index) in regimes"
                                                :class="{ 'table-info': inEdition == regime.id }">
                                                <th scope="row">{{ regime.id }}</th>
                                                <td>{{ regime.name }}</td>
                                                <td>
                                                    <button class="btn btn-info btn-icon-split mr-2"
                                                        v-on:click="edit(regime)">
                                                        <span class="icon text-white-50">
                                                            <i class="fas fa-edit"></i>
                                                        </span>
                                                        <span class="text">Editar</span>
                                                    </button>

                                                    <Modal :key="index"
                                                        :modal-title="'Confirmar Exclusão de ' + regime.name"
                                                        :ok-botton-callback="deleteRegime"
                                                        :ok-botton-callback-param="regime.id"
                                                        btn-class="btn btn-danger btn-icon-split">
                                                        <template v-slot:button>
                                                            <span class="icon text-white-50">
                                                                <i class="fas fa-trash"></i>
                                                            </span>
                                                            <span class="text">Excluir</span>
                                                        </template>
                                                        <template v-slot:content>
                                                            Tem certeza que deseja apagar esse registro?
                                                        </template>
                                                    </Modal>

                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </AuthenticatedLayout>
</template>
